from __future__ import annotations
from pathlib import Path
from .registry import Registry
from .context import build_context
from .v2 import FROZEN_RESEARCH_SHA, V2_GENERATED_MARKER, build_context_packets, read_manifest

GEN='<!-- GENERATED BY SportsBrainMemory V1: DO NOT EDIT -->'

def _write(path:Path,text:str):
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(text.rstrip()+"\n",encoding='utf-8')

def _finding_rows(reg,statuses):
    return [o for o in reg.objects if o.object_type=='finding' and o.status in statuses]

def render_all(root:Path):
    reg=Registry(root).scan()
    active=[o for o in reg.objects if o.object_type=='task' and o.status in {'approved','active'}]
    if len(active)>1:
        raise RuntimeError('multiple active tasks')

    if active:
        t=active[0]
        current_task=(
            '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
            f'{GEN}\n{V2_GENERATED_MARKER}\n# Current Builder Task\n\n'
            f'**{t.object_id} — {t.meta.get("title","")}**\n\n'
            f'Canonical record: [[{t.relpath[:-3]}]]\n'
        )
    else:
        current_task=(
            '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
            f'{GEN}\n{V2_GENERATED_MARKER}\n# Current Builder Task\n\n'
            '**NONE**\n\nNo CEO-approved Builder task is active. Builder MUST STOP. Draft tasks are planning objects only.\n'
        )
    _write(root/'CURRENT_TASK.md',current_task)

    states=[o for o in reg.objects if o.object_type=='project-state' and o.status=='current']
    if len(states)!=1:
        raise RuntimeError(f'expected one current project-state, got {len(states)}')
    s=states[0]
    ws=[o for o in reg.objects if o.object_type=='workstream']
    ws_lines='\n'.join(
        f'- **{o.meta.get("workstream",o.object_id)}** — {o.status}'
        for o in sorted(ws,key=lambda x:x.relpath)
    )
    task_label='NONE' if not active else active[0].object_id
    def _meta_lines(key, fallback='- None'):
        value = s.meta.get(key)
        if isinstance(value, list):
            return '\n'.join(f'- {item}' for item in value) or fallback
        return f'- {value}' if value else fallback
    current_state=(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
        f'{GEN}\n{V2_GENERATED_MARKER}\n# Current State\n\n## Technical baseline\n\n'
        f'- Source release SHA: `{s.meta.get("source_release_sha")}`\n'
        f'- Runtime/data HEAD observed: `{s.meta.get("runtime_data_head")}`\n'
        f'- Audited source main SHA: `{read_manifest(root).get("source_main_sha")}`\n'
        f'- Frozen Research SHA: `{FROZEN_RESEARCH_SHA}` — completion event `EVT-20260913-010`\n'
        '- 2425 and 2526: **SEALED**; Top-5 live activation: **NOT APPROVED**.\n'
        '- P0-A production verification: **VERIFIED**\n'
        f'- Current Builder task: **{task_label}**\n'
        '- Product score: **RECOMPUTE REQUIRED** — historical scores remain prior evidence only.\n\n'
        '## Workstreams\n\n'
        f'{ws_lines}\n\n'
        '## Open / merge-ready evidence\n\n'
        f'{_meta_lines("open_prs")}\n\n'
        '## Active workstreams\n\n'
        f'{_meta_lines("active_workstreams")}\n\n'
        '## Blockers\n\n'
        f'{_meta_lines("blocked_workstreams")}\n\n'
        f'## Next production milestone\n\n{s.meta.get("next_production_milestone", "- Not recorded")}\n\n'
        'Canonical technical state: [[state/records/STATE-20260816-001]]\n'
    )
    current_state = current_state.replace('[[state/records/STATE-20260816-001]]', f'[[{s.relpath[:-3]}]]')
    _write(root/'CURRENT_STATE.md',current_state)

    openf=_finding_rows(reg,{'open','observed','confirmed','accepted','in_progress','resolved_candidate'})
    resolved=_finding_rows(reg,{'resolved','resolved_production','closed'})

    def finding_view(title,items):
        links='\n'.join(
            f'- [[{o.relpath[:-3]}]]'
            for o in sorted(items,key=lambda x:x.object_id or '')
        ) or '- None'
        return (
            '---\ntype: finding-index\nstatus: current\ngenerated: true\n'
            f'count: "{len(items)}"\n---\n{GEN}\n# {title}\n\n{links}\n'
        )

    _write(root/'findings/OPEN.md',finding_view('Open Findings',openf))
    _write(root/'findings/RESOLVED.md',finding_view('Resolved Findings',resolved))

    p0_open=[o for o in openf if str(o.meta.get('severity','')).upper()=='P0']
    blockers='\n'.join(
        f'- [[{o.relpath[:-3]}]]'
        for o in sorted(p0_open,key=lambda x:x.object_id or '')
    ) or '- None'
    _write(root/'CURRENT_BLOCKERS.md',(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
        f'{GEN}\n{V2_GENERATED_MARKER}\n# Current Blockers\n\n## Open P0 findings\n\n{blockers}\n\n'
        f'- Audited source main SHA: `{read_manifest(root).get("source_main_sha")}`\n'
        f'- Research completion event: `EVT-20260913-010`; frozen SHA: `{FROZEN_RESEARCH_SHA}`.\n'
        '- 2425 and 2526 remain **SEALED**; Top-5 live activation remains **NOT APPROVED**.\n\n'
        'P0-A historical findings 001–004 are resolved production and are not blockers.\n'
    ))
    _STATUS_RANK={'active':0,'planned_ready':1,'planned':2}
    _WS_RANK={'P0-A':0,'P0-B':1,'P0-C':2,'P0-D':3,'MODEL-INTEGRITY':4,'WAVE-3D':5}
    prio_lines=[]
    n=1
    active_ws=active[0].meta.get('workstream') if active else None
    if active:
        t=active[0]
        prio_lines.append(f'{n}. Execute **{t.object_id}** — {t.meta.get("title","")}.')
        n+=1
    pending_ws=[o for o in reg.objects
                if o.object_type=='workstream'
                and o.status not in {'closed'}
                and o.meta.get('workstream',o.object_id)!=active_ws]
    pending_ws.sort(key=lambda o:(_STATUS_RANK.get(o.status,9),_WS_RANK.get(o.meta.get('workstream',o.object_id),99),o.relpath))
    for o in pending_ws:
        ws_name=o.meta.get('workstream',o.object_id)
        prio_lines.append(f'{n}. Execute {ws_name} workstream.')
        n+=1
    priorities_body='\n'.join(prio_lines) if prio_lines else '- All workstreams complete.'
    _write(root/'CURRENT_PRIORITIES.md',(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
        f'{GEN}\n{V2_GENERATED_MARKER}\n# Current Priorities\n\n'
        f'- Audited source main SHA: `{read_manifest(root).get("source_main_sha")}`\n'
        f'- Frozen Research SHA: `{FROZEN_RESEARCH_SHA}`; completion event: `EVT-20260913-010`.\n'
        '- 2425 and 2526 remain **SEALED**; Top-5 live activation remains **NOT APPROVED**.\n\n'
        f'{priorities_body}\n'
        '- Keep the formal **72h Stability Soak** deferred until the external quota dependency is resolved.\n'
        '- Historical P0 order remains unchanged as a phase sequence; it is not a reason to reactivate completed workstreams.\n'
    ))

    tasks=[o for o in reg.objects if o.object_type=='task']
    tasklines='\n'.join(
        f'| {o.object_id} | {o.status} | {o.meta.get("workstream","")} | {o.meta.get("budget_class","")} |'
        for o in sorted(tasks,key=lambda x:x.object_id or '')
    )
    _write(root/'views/TASKS.md',(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
        f'{GEN}\n{V2_GENERATED_MARKER}\n# Builder Tasks\n\n| Task | Status | Workstream | Budget |\n'
        '|---|---|---|---|\n'
        f'{tasklines}\n'
    ))

    source=[]
    for o in reg.objects:
        sp=o.meta.get('source_paths')
        if isinstance(sp,list):
            for x in sp:
                source.append((str(x),o.object_id or o.relpath))
        elif isinstance(sp,str):
            source.append((sp,o.object_id or o.relpath))
    sl='\n'.join(f'| `{p}` | {oid} |' for p,oid in sorted(source))
    _write(root/'views/SOURCE_MAP.md',(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
        f'{GEN}\n{V2_GENERATED_MARKER}\n# SportsBrain Source Map\n\n| Source path | Memory object |\n|---|---|\n{sl}\n'
    ))

    _write(root/'views/COVERAGE.md',(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
        f'{GEN}\n{V2_GENERATED_MARKER}\n# Coverage View\n\n'
        'Coverage target: **Invariant → implementation boundary → deterministic test → exact CI → production evidence**.\n\n'
        'This V1 foundation records task-level invariants and source boundaries. Product task closure must add exact '
        'test/CI/production verification evidence; a Builder report alone cannot close a production finding.\n'
    ))

    mocs={
      'Product':['product/VISION_AND_PRINCIPLES','product/ROADMAP','product/SCORECARD','domains/PRODUCT_CONTRACT'],
      'Architecture':['architecture/SYSTEM_MAP','architecture/DATA_AND_PERSISTENCE','architecture/EXECUTION_AND_RELEASE','architecture/TRUTH_AND_WRITERS','architecture/OPERATIONAL_KNOWLEDGE_BASE'],
      'Betting':['domains/LEDGER_AND_MEASUREMENT','components/CMP-BETTING'],
      'Tennis':['domains/TENNIS','components/CMP-TENNIS-MODEL','models/MOD-TENNIS-LGBM'],
      'Football':['domains/FOOTBALL','domains/TOP5'],
      'Nations-League':['domains/NATIONS_LEAGUE','findings/NEGATIVE_EVIDENCE'],
      'Models':['domains/MODELS','domains/MODEL_RESEARCH','models/MOD-TENNIS-LGBM','findings/NEGATIVE_EVIDENCE'],
      'Data':['architecture/DATA_AND_PERSISTENCE','domains/DATA_AND_PROVIDERS','datasets/DAT-TENNIS-MEAS'],
      'Runtime':['architecture/EXECUTION_AND_RELEASE','domains/PRODUCTION_OPERATIONS','views/SOURCE_MAP'],
      'Monitoring':['domains/MONITORING_AND_RECOVERY','domains/PRODUCTION_OPERATIONS','components/CMP-MONITORING','runbooks/INDEX'],
      'PWA':['domains/PWA_AND_WORKER','components/CMP-PUBLICATION'],
      'Governance':['architecture/TRUTH_AND_WRITERS','domains/GOVERNANCE','_meta/CANONICAL_OWNERSHIP','_meta/SOURCE_HIERARCHY'],
      'Security-Privacy':['domains/SECURITY_AND_PRIVACY','components/CMP-PUBLICATION'],
      'Builder':['builder/START_HERE','builder/ONBOARDING_30_MIN','domains/BUILDERS','builder/CLAUDE_RUNBOOK','views/TASKS'],
      'History':['history/AUDIT_INDEX','history/INCIDENT_TIMELINE'],
      'Memory':['00_HOME','architecture/OPERATIONAL_KNOWLEDGE_BASE','evidence/PR_EVIDENCE_INDEX','templates/INDEX','_meta/OBJECT_MODEL','_meta/RELATION_MODEL','_meta/GENERATED_VIEW_POLICY'],
    }
    for name,links in mocs.items():
        body='\n'.join(f'- [[{x}]]' for x in links)
        _write(root/f'mocs/{name}.md',(
            '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
            f'{GEN}\n{V2_GENERATED_MARKER}\n# {name} MOC\n\n{body}\n'
        ))

    home=(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
        f'{GEN}\n{V2_GENERATED_MARKER}\n# SportsBrain Home\n\n## Now\n\n'
        '- Memory version: **V2 operational knowledge base**\n'
        f'- Source release: `{s.meta.get("source_release_sha")}`\n'
        f'- Runtime/data HEAD observed: `{s.meta.get("runtime_data_head")}`\n'
        f'- Audited source main SHA: `{read_manifest(root).get("source_main_sha")}`\n'
        f'- Frozen Research SHA: `{FROZEN_RESEARCH_SHA}`; completion event: `EVT-20260913-010`.\n'
        '- 2425 and 2526 remain **SEALED**; Top-5 live activation remains **NOT APPROVED**.\n'
        f'- Current Builder task: **{task_label}**\n'
        f'- Open P0 findings: **{len(p0_open)}**\n'
        '- Product score: **RECOMPUTE REQUIRED**\n'
        '- Production, shadow/research, and historical evidence remain separate.\n\n'
        '- Builder 1 — Top-5 Shadow Integration; Builder 2 — Production/Activation Readiness; Builder 3 — Memory/Observability.\n'
        '- Builder 4/5 dispatch lanes are documented as governance scope, not an invented active assignment.\n\n'
        '## What is live / what is gated\n\n'
        '- PWA and Worker/public surfaces are documented under [[domains/PRODUCTION_OPERATIONS]].\n'
        '- Nations League is shadow-only and non-actionable: [[domains/NATIONS_LEAGUE]].\n'
        '- Top-5 activation remains disabled and CEO-gated: [[domains/TOP5]].\n'
        '- PostHog PWA analytics is branch-only at PR #221 until merge/deploy.\n\n'
        '## Attention\n\n- [[CURRENT_BLOCKERS]]\n- [[CURRENT_PRIORITIES]]\n- [[views/TASKS]]\n- [[views/COVERAGE]]\n\n'
        '## Start here\n\n- [[architecture/OPERATIONAL_KNOWLEDGE_BASE]]\n- [[evidence/PR_EVIDENCE_INDEX]]\n- [[runbooks/INDEX]]\n- [[builder/ONBOARDING_30_MIN]]\n\n'
        '## Maps of Content\n\n'
        + '\n'.join(f'- [[mocs/{n}]]' for n in mocs) + '\n'
    )
    _write(root/'00_HOME.md',home)
    if active:
        ctx=build_context(root,active[0].object_id)
        _write(root/'builder/CURRENT_CONTEXT_PACKET.md',ctx.text)
    else:
        _write(root/'builder/CURRENT_CONTEXT_PACKET.md',(
            f'{GEN}\n{V2_GENERATED_MARKER}\n# Current Context Packet\n\n'
            '**NONE** — no approved Builder task is active. Generate a packet only after CEO approval of a task.\n'
        ))
    build_context_packets(root)
    return {'open_findings':len(openf),'resolved_findings':len(resolved),'tasks':len(tasks),'active_tasks':len(active)}
