from __future__ import annotations
from pathlib import Path
from .registry import Registry

GEN='<!-- GENERATED BY SportsBrainMemory V1: DO NOT EDIT -->'

def _write(path:Path,text:str):
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(text.rstrip()+"\n",encoding='utf-8')

def _finding_rows(reg,statuses):
    return [o for o in reg.objects if o.object_type=='finding' and o.status in statuses]

def render_all(root:Path):
    reg=Registry(root).scan()
    active=[o for o in reg.objects if o.object_type=='task' and o.status in {'approved','active'}]
    if len(active)>1:
        raise RuntimeError('multiple active tasks')

    if active:
        t=active[0]
        current_task=(
            '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
            f'{GEN}\n# Current Builder Task\n\n'
            f'**{t.object_id} — {t.meta.get("title","")}**\n\n'
            f'Canonical record: [[{t.relpath[:-3]}]]\n'
        )
    else:
        current_task=(
            '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
            f'{GEN}\n# Current Builder Task\n\n'
            '**NONE**\n\nNo CEO-approved Builder task is active. Builder MUST STOP. Draft tasks are planning objects only.\n'
        )
    _write(root/'CURRENT_TASK.md',current_task)

    states=[o for o in reg.objects if o.object_type=='project-state' and o.status=='current']
    if len(states)!=1:
        raise RuntimeError(f'expected one current project-state, got {len(states)}')
    s=states[0]
    ws=[o for o in reg.objects if o.object_type=='workstream']
    ws_lines='\n'.join(
        f'- **{o.meta.get("workstream",o.object_id)}** — {o.status}'
        for o in sorted(ws,key=lambda x:x.relpath)
    )
    task_label='NONE' if not active else active[0].object_id
    current_state=(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n'
        'last_updated: 2026-08-16T13:04:00+02:00\n---\n'
        f'{GEN}\n# Current State\n\n## Technical baseline\n\n'
        f'- Source release SHA: `{s.meta.get("source_release_sha")}`\n'
        f'- Runtime/data HEAD observed: `{s.meta.get("runtime_data_head")}`\n'
        '- P0-A production verification: **VERIFIED**\n'
        f'- Current Builder task: **{task_label}**\n'
        '- Product score: **RECOMPUTE REQUIRED** — historical 4.1 remains prior evidence only.\n\n'
        '## Workstreams\n\n'
        f'{ws_lines}\n\n'
        'Canonical technical state: [[state/records/STATE-20260816-001]]\n'
    )
    _write(root/'CURRENT_STATE.md',current_state)

    openf=_finding_rows(reg,{'open','observed','confirmed','accepted','in_progress','resolved_candidate'})
    resolved=_finding_rows(reg,{'resolved','resolved_production','closed'})

    def finding_view(title,items):
        links='\n'.join(
            f'- [[{o.relpath[:-3]}]]'
            for o in sorted(items,key=lambda x:x.object_id or '')
        ) or '- None'
        return (
            '---\ntype: finding-index\nstatus: current\ngenerated: true\n'
            f'count: "{len(items)}"\n---\n{GEN}\n# {title}\n\n{links}\n'
        )

    _write(root/'findings/OPEN.md',finding_view('Open Findings',openf))
    _write(root/'findings/RESOLVED.md',finding_view('Resolved Findings',resolved))

    p0_open=[o for o in openf if str(o.meta.get('severity','')).upper()=='P0']
    blockers='\n'.join(
        f'- [[{o.relpath[:-3]}]]'
        for o in sorted(p0_open,key=lambda x:x.object_id or '')
    ) or '- None'
    _write(root/'CURRENT_BLOCKERS.md',(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
        f'{GEN}\n# Current Blockers\n\n## Open P0 findings\n\n{blockers}\n\n'
        'P0-A historical findings 001–004 are resolved production and are not blockers.\n'
    ))
    _write(root/'CURRENT_PRIORITIES.md',(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
        f'{GEN}\n# Current Priorities\n\n'
        '1. Accept/install SportsBrainMemory V1 using `TASK-MEM-V1-ACCEPT`.\n'
        '2. Execute P0-B Monitoring Truth tasks B1→B4.\n'
        '3. Execute P0-C Privacy/Persistence.\n'
        '4. Execute P0-D Writer Governance.\n'
        '5. Execute MODEL-1 → MEAS-1 → MODEL-2.\n'
    ))

    tasks=[o for o in reg.objects if o.object_type=='task']
    tasklines='\n'.join(
        f'| {o.object_id} | {o.status} | {o.meta.get("workstream","")} | {o.meta.get("budget_class","")} |'
        for o in sorted(tasks,key=lambda x:x.object_id or '')
    )
    _write(root/'views/TASKS.md',(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
        f'{GEN}\n# Builder Tasks\n\n| Task | Status | Workstream | Budget |\n'
        '|---|---|---|---|\n'
        f'{tasklines}\n'
    ))

    source=[]
    for o in reg.objects:
        sp=o.meta.get('source_paths')
        if isinstance(sp,list):
            for x in sp:
                source.append((str(x),o.object_id or o.relpath))
        elif isinstance(sp,str):
            source.append((sp,o.object_id or o.relpath))
    sl='\n'.join(f'| `{p}` | {oid} |' for p,oid in sorted(source))
    _write(root/'views/SOURCE_MAP.md',(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
        f'{GEN}\n# SportsBrain Source Map\n\n| Source path | Memory object |\n|---|---|\n{sl}\n'
    ))

    _write(root/'views/COVERAGE.md',(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
        f'{GEN}\n# Coverage View\n\n'
        'Coverage target: **Invariant → implementation boundary → deterministic test → exact CI → production evidence**.\n\n'
        'This V1 foundation records task-level invariants and source boundaries. Product task closure must add exact '
        'test/CI/production verification evidence; a Builder report alone cannot close a production finding.\n'
    ))

    mocs={
      'Product':['product/VISION_AND_PRINCIPLES','product/ROADMAP','product/SCORECARD'],
      'Architecture':['architecture/SYSTEM_MAP','architecture/DATA_AND_PERSISTENCE','architecture/EXECUTION_AND_RELEASE','architecture/TRUTH_AND_WRITERS'],
      'Betting':['domains/LEDGER_AND_MEASUREMENT','components/CMP-BETTING'],
      'Tennis':['domains/TENNIS','components/CMP-TENNIS-MODEL','models/MOD-TENNIS-LGBM'],
      'Football':['domains/FOOTBALL'],
      'Models':['domains/MODELS','models/MOD-TENNIS-LGBM'],
      'Data':['architecture/DATA_AND_PERSISTENCE','datasets/DAT-TENNIS-MEAS'],
      'Runtime':['architecture/EXECUTION_AND_RELEASE','views/SOURCE_MAP'],
      'Monitoring':['domains/MONITORING_AND_RECOVERY','components/CMP-MONITORING'],
      'PWA':['domains/PWA_AND_WORKER','components/CMP-PUBLICATION'],
      'Governance':['architecture/TRUTH_AND_WRITERS','_meta/CANONICAL_OWNERSHIP'],
      'Security-Privacy':['domains/SECURITY_AND_PRIVACY','components/CMP-PUBLICATION'],
      'Builder':['builder/START_HERE','builder/CLAUDE_RUNBOOK','views/TASKS'],
      'History':['history/AUDIT_INDEX','history/INCIDENT_TIMELINE'],
      'Memory':['00_HOME','_meta/OBJECT_MODEL','_meta/RELATION_MODEL','_meta/GENERATED_VIEW_POLICY'],
    }
    for name,links in mocs.items():
        body='\n'.join(f'- [[{x}]]' for x in links)
        _write(root/f'mocs/{name}.md',(
            '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
            f'{GEN}\n# {name} MOC\n\n{body}\n'
        ))

    home=(
        '---\ntype: generated-view\nstatus: current\ngenerated: true\n---\n'
        f'{GEN}\n# SportsBrain Home\n\n## Now\n\n'
        '- Memory version: **V1.0.0 acceptance-ready**\n'
        f'- Source release: `{s.meta.get("source_release_sha")}`\n'
        f'- Runtime/data HEAD observed: `{s.meta.get("runtime_data_head")}`\n'
        f'- Current Builder task: **{task_label}**\n'
        f'- Open P0 findings: **{len(p0_open)}**\n'
        '- Product score: **RECOMPUTE REQUIRED**\n\n'
        '## Attention\n\n- [[CURRENT_BLOCKERS]]\n- [[CURRENT_PRIORITIES]]\n- [[views/TASKS]]\n- [[views/COVERAGE]]\n\n'
        '## Maps of Content\n\n'
        + '\n'.join(f'- [[mocs/{n}]]' for n in mocs) + '\n'
    )
    _write(root/'00_HOME.md',home)
    _write(root/'builder/CURRENT_CONTEXT_PACKET.md',(
        f'{GEN}\n# Current Context Packet\n\n'
        '**NONE** — no approved Builder task is active. Generate a packet only after CEO approval of a task.\n'
    ))
    return {'open_findings':len(openf),'resolved_findings':len(resolved),'tasks':len(tasks),'active_tasks':len(active)}
