"""Deterministic, non-canonical Semantic Link Graph V2.

The graph is a projection.  Canonical records are read but never rewritten;
runtime observer data is optional and is always marked as derived evidence.
Only explicit structured fields and authored wikilinks create relations.
"""
from __future__ import annotations

from collections import Counter, defaultdict, deque
from dataclasses import dataclass, field
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import tempfile
import time
from typing import Any, Iterable

from .frontmatter import parse_frontmatter
from .governance import BUILDER_NUMBERS, BUILDER_NUMBER_SET


GRAPH_SCHEMA = 2
GRAPH_RELATIVE_ROOT = "views/graph"
GRAPH_MARKER = "<!-- GENERATED BY SportsBrainMemory Semantic Link Graph V2: NONCANONICAL DERIVED VIEW -->"

NAMESPACES = (
    "EVENT", "DECISION", "EVIDENCE", "FINDING", "VERIFICATION", "TASK",
    "WORKSTREAM", "BUILDER", "PROVIDER", "MODEL", "DATASET", "PR",
    "COMMIT", "INVARIANT", "BLOCKER", "REPOSITORY", "DOMAIN",
    "STATE", "COMPONENT", "JOB", "WRITER", "ARCHITECTURE", "META",
)

ID_NAMESPACE = {
    "EVT": "EVENT", "DEC": "DECISION", "EVD": "EVIDENCE", "FND": "FINDING",
    "VER": "VERIFICATION", "TASK": "TASK", "WS": "WORKSTREAM", "PRV": "PROVIDER",
    "MOD": "MODEL", "DAT": "DATASET", "STATE": "STATE", "CMP": "COMPONENT",
    "JOB": "JOB", "WRT": "WRITER", "BLK": "BLOCKER",
}

FIELD_RELATIONS: dict[str, tuple[str, str | None]] = {
    "affected_workstreams": ("affected_workstream", "WORKSTREAM"),
    "workstream": ("workstream", "WORKSTREAM"),
    "workstreams": ("workstream", "WORKSTREAM"),
    "findings": ("finding", "FINDING"),
    "finding": ("finding", "FINDING"),
    "decisions": ("decision", "DECISION"),
    "decision": ("decision", "DECISION"),
    "evidence": ("evidence", "EVIDENCE"),
    "verified_by": ("verification", "VERIFICATION"),
    "verifications": ("verification", "VERIFICATION"),
    "verification": ("verification", "VERIFICATION"),
    "resolved_by": ("resolved_by", None),
    "invariants": ("invariant", "INVARIANT"),
    "invariant": ("invariant", "INVARIANT"),
    "supersedes": ("supersedes", None),
    "superseded_by": ("superseded_by", None),
    "depends_on": ("depends_on", None),
    "related": ("related", None),
    "provider": ("provider", "PROVIDER"),
    "providers": ("provider", "PROVIDER"),
    "model": ("model", "MODEL"),
    "models": ("model", "MODEL"),
    "model_id": ("model", "MODEL"),
    "dataset": ("dataset", "DATASET"),
    "datasets": ("dataset", "DATASET"),
    "blocked_by": ("blocked_by", "BLOCKER"),
    "blocks": ("blocks", "BLOCKER"),
    "blockers": ("blocker", "BLOCKER"),
    "source_candidate_id": ("source_evidence", "EVIDENCE"),
}

SHA_RE = re.compile(r"(?<![0-9a-f])([0-9a-f]{40})(?![0-9a-f])")
PR_RE = re.compile(r"(?:github\s+)?(?:pull\s+request|PR)\s*#?(\d+)", re.IGNORECASE)
ID_RE = re.compile(r"\b(?:EVT|DEC|EVD|FND|VER|TASK|WS|PRV|MOD|DAT|STATE|CMP|JOB|WRT|BLK)-[A-Za-z0-9][A-Za-z0-9-]*\b")
WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")
BUILDER_RE = re.compile(r"^Builder ([1-5])$", re.IGNORECASE)

CANONICAL_SCAN_DIRS = (
    "_meta", "architecture", "builder", "components", "datasets", "decisions",
    "domains", "events", "evidence", "findings", "history", "invariants", "jobs",
    "models", "product", "providers", "state", "tasks", "verifications", "workstreams",
    "writers",
)
SKIP_SCAN_PARTS = {".git", ".memory-build", ".memory-backups", "__pycache__", ".obsidian", "_live"}
SKIP_GENERATED_PARTS = {"views", "mocs"}
SKIP_GENERATED_NAMES = {
    "00_HOME.md", "CURRENT_STATE.md", "CURRENT_PRIORITIES.md", "CURRENT_BLOCKERS.md",
    "CURRENT_TASK.md", "VALIDATION_REPORT.md",
}


@dataclass
class GraphIssue:
    severity: str
    code: str
    message: str
    path: str | None = None

    def as_dict(self) -> dict[str, Any]:
        return {"severity": self.severity, "code": self.code, "message": self.message, "path": self.path}


@dataclass
class Entity:
    namespace: str
    stable_id: str
    label: str
    source_paths: set[str] = field(default_factory=set)
    provenance: str = "CANONICAL"
    canonical: bool = True
    source_type: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    target_root: str = GRAPH_RELATIVE_ROOT

    @property
    def key(self) -> str:
        return f"{self.namespace}:{self.stable_id}"

    @property
    def target(self) -> str:
        return f"{self.target_root}/entities/{self.namespace}/{_safe_slug(self.stable_id)}"

    def as_dict(self) -> dict[str, Any]:
        return {
            "entity_key": self.key,
            "namespace": self.namespace,
            "stable_id": self.stable_id,
            "label": self.label,
            "source_paths": sorted(self.source_paths),
            "provenance": self.provenance,
            "canonical": self.canonical,
            "source_type": self.source_type,
            "metadata": _stable_json(self.metadata),
            "target": self.target,
        }


@dataclass
class GraphEdge:
    source: str
    relation: str
    target: str
    source_path: str
    field: str
    raw_target: str
    provenance: str
    evidence: list[dict[str, str]] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "source": self.source,
            "relation": self.relation,
            "target": self.target,
            "source_path": self.source_path,
            "field": self.field,
            "raw_target": self.raw_target,
            "provenance": self.provenance,
            "evidence": sorted(self.evidence, key=lambda item: (item.get("path", ""), item.get("field", ""))),
        }


@dataclass
class GraphValidation:
    errors: int
    warnings: int
    issues: list[GraphIssue]
    health: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "errors": self.errors,
            "warnings": self.warnings,
            "issues": [issue.as_dict() for issue in self.issues],
            "health": self.health,
        }


def _stable_json(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): _stable_json(value[key]) for key in sorted(value, key=str)}
    if isinstance(value, (list, tuple, set)):
        return [_stable_json(item) for item in sorted(value, key=lambda item: json.dumps(_stable_json(item), sort_keys=True, ensure_ascii=True))]
    return value


def _safe_slug(value: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9._-]+", "_", str(value)).strip("._")
    return slug or "UNRESOLVED"


def _normal_text(value: Any) -> str:
    return " ".join(str(value).split()).strip()


def _normal_link_root(value: Any) -> str:
    normalized = str(value or "").replace("\\", "/").strip().strip("/")
    if not normalized or normalized == ".":
        raise ValueError("graph link_root must be a non-empty relative path")
    if any(part in {"", ".", ".."} for part in normalized.split("/")):
        raise ValueError("graph link_root must not contain empty, dot, or parent path components")
    return normalized


def _parse_time(value: Any) -> datetime | None:
    if not isinstance(value, str) or not value.strip():
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(timezone.utc)
    except ValueError:
        return None


def _freshness_state(updated_at: Any, current: datetime) -> str:
    updated = _parse_time(updated_at)
    if updated is None:
        return "STALE"
    hours = max(0.0, (current - updated).total_seconds() / 3600.0)
    if hours <= 6:
        return "FRESH"
    if hours <= 24:
        return "AGING"
    return "STALE"


def _json_file(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _canonical_input_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for directory in CANONICAL_SCAN_DIRS:
        base = root / directory
        if not base.exists():
            continue
        for path in sorted(base.rglob("*")):
            if not path.is_file() or path.suffix not in {".md", ".json"}:
                continue
            rel_parts = path.relative_to(root).parts
            if any(part in SKIP_SCAN_PARTS or part in SKIP_GENERATED_PARTS for part in rel_parts):
                continue
            if path.name in SKIP_GENERATED_NAMES:
                continue
            files.append(path)
    for name in ("README.md", "SETUP.md", "BOOTSTRAP.md", "CLAUDE.md"):
        path = root / name
        if path.exists():
            files.append(path)
    return sorted(set(files))


def canonical_input_digest(root: Path) -> str:
    digest = hashlib.sha256()
    for path in _canonical_input_files(root):
        rel = path.relative_to(root).as_posix()
        digest.update(rel.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def canonical_event_digest(root: Path) -> str:
    digest = hashlib.sha256()
    for path in sorted((root / "events" / "records").glob("*.json")) if (root / "events" / "records").exists() else []:
        digest.update(path.name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def _namespace_for_path(rel: str, meta: dict[str, Any]) -> str | None:
    path = Path(rel)
    parts = path.parts
    if "records" in parts:
        parent = parts[parts.index("records") - 1] if parts.index("records") else ""
        return {
            "decisions": "DECISION", "evidence": "EVIDENCE", "findings": "FINDING",
            "verifications": "VERIFICATION", "tasks": "TASK", "state": "STATE",
        }.get(parent)
    if parts:
        direct = {
            "workstreams": "WORKSTREAM", "providers": "PROVIDER", "models": "MODEL",
            "datasets": "DATASET", "domains": "DOMAIN", "invariants": "INVARIANT",
            "components": "COMPONENT", "jobs": "JOB", "writers": "WRITER",
            "architecture": "ARCHITECTURE", "_meta": "META", "history": "META",
        }.get(parts[0])
        if direct:
            return direct
    object_type = str(meta.get("type", "")).strip().strip('"').lower()
    return {
        "decision": "DECISION", "evidence": "EVIDENCE", "finding": "FINDING",
        "verification": "VERIFICATION", "task": "TASK", "workstream": "WORKSTREAM",
        "provider": "PROVIDER", "model": "MODEL", "dataset": "DATASET",
        "domain": "DOMAIN", "component": "COMPONENT", "job": "JOB",
        "writer-class": "WRITER", "project-state": "STATE",
    }.get(object_type)


def _label_from_document(path: Path, meta: dict[str, Any], body: str, stable_id: str) -> str:
    for key in ("title", "name", "summary"):
        value = meta.get(key)
        if isinstance(value, str) and value.strip():
            return _normal_text(value)
    heading = re.search(r"^#\s+(.+)$", body, re.MULTILINE)
    return _normal_text(heading.group(1)) if heading else stable_id


class SemanticGraph:
    """In-memory graph registry and deterministic projection builder."""

    def __init__(
        self,
        root: Path,
        *,
        vault: Path | None = None,
        include_runtime: bool = False,
        output_root: Path | None = None,
        link_root: str | None = None,
        reference_time: str | None = None,
    ) -> None:
        self.root = root.resolve()
        self.vault = vault.resolve() if vault else None
        self.include_runtime = include_runtime and self.vault is not None
        self.output_root = self._default_output_root(output_root)
        self.link_root = _normal_link_root(link_root or self._default_link_root(self.output_root))
        self.reference_time = _parse_time(reference_time) or datetime.now(timezone.utc)
        self.entities: dict[str, Entity] = {}
        self.aliases: dict[tuple[str | None, str], str] = {}
        self.path_entities: dict[str, str] = {}
        self.edges: dict[tuple[str, str, str], GraphEdge] = {}
        self.unresolved: list[dict[str, Any]] = []
        self.issues: list[GraphIssue] = []
        self.records: list[tuple[str, dict[str, Any], str, bool, str, str]] = []
        self.generated_at = ""

    def _default_output_root(self, output_root: Path | None) -> Path:
        if output_root is not None:
            return output_root.resolve()
        if self.include_runtime and self.vault is not None:
            return (self.vault / "_live" / "graph").resolve()
        return (self.root / GRAPH_RELATIVE_ROOT).resolve()

    def _default_link_root(self, output_root: Path) -> str:
        if self.vault is not None:
            try:
                return output_root.relative_to(self.vault).as_posix()
            except ValueError:
                pass
        try:
            return output_root.relative_to(self.root).as_posix()
        except ValueError:
            return GRAPH_RELATIVE_ROOT

    def configure_output(self, output_root: Path, link_root: str | None = None) -> None:
        """Configure where this projection is materialized and linked."""
        self.output_root = output_root.resolve()
        self.link_root = _normal_link_root(link_root or self._default_link_root(self.output_root))
        for entity in self.entities.values():
            entity.target_root = self.link_root

    def build(self) -> "SemanticGraph":
        started = time.perf_counter()
        self.entities.clear()
        self.aliases.clear()
        self.path_entities.clear()
        self.edges.clear()
        self.unresolved.clear()
        self.issues.clear()
        self.records.clear()
        self._index_canonical_sources()
        self._seed_builder_identities()
        for entity_key, payload, source_path, canonical, provenance, body in self.records:
            self._register_structured_relations(entity_key, payload, source_path, canonical, provenance)
            self._register_body_links(entity_key, body, source_path, canonical, provenance)
        if self.include_runtime:
            self._index_runtime_sources()
        timestamps = []
        manifest = _json_file(self.root / "_meta" / "MEMORY_V2.json")
        if isinstance(manifest, dict):
            timestamps.append(manifest.get("canonical_updated_at"))
        timestamps.extend(payload.get("timestamp") for _, payload, _, _, _, _ in self.records)
        if self.include_runtime and self.vault:
            runtime_inputs = {"SOURCE_OBSERVER.json", "SOURCE_CANDIDATES.json", "BUILDER_HANDOFFS.json", "BLOCKERS.json"}
            for path in sorted((self.vault / "_live").glob("*.json")):
                if path.name not in runtime_inputs:
                    continue
                payload = _json_file(path)
                if isinstance(payload, dict):
                    timestamps.append(payload.get("generated_at"))
                    timestamps.append(payload.get("observed_at"))
        parsed = [item for item in (_parse_time(value) for value in timestamps) if item]
        self.generated_at = max(parsed).isoformat().replace("+00:00", "Z") if parsed else "1970-01-01T00:00:00Z"
        # Keep a small performance datum for the CLI without putting wall time in the semantic digest.
        self.build_seconds = time.perf_counter() - started
        return self

    def _seed_builder_identities(self) -> None:
        for number in BUILDER_NUMBERS:
            self._add_entity(
                "BUILDER", f"BUILDER-{number}", f"Builder {number}",
                "governance/builder-identities", "GOVERNED_IDENTITY", False,
                metadata={"operational_role": "evidence-derived from explicit handoff only"},
                aliases=(str(number), f"Builder {number}", f"BUILDER: {number}"),
            )

    def _index_canonical_sources(self) -> None:
        for path in _canonical_input_files(self.root):
            rel = path.relative_to(self.root).as_posix()
            if path.suffix == ".json":
                payload = _json_file(path)
                if not isinstance(payload, dict):
                    self.issues.append(GraphIssue("ERROR", "SOURCE_JSON_INVALID", "canonical JSON source is not an object", rel))
                    continue
                event_id = payload.get("event_id")
                if rel.startswith("events/") and isinstance(event_id, str):
                    namespace = "EVENT"
                    canonical = bool(payload.get("canonical", "/records/" in rel))
                    provenance = "CANONICAL" if canonical else "CANDIDATE_CANONICAL_BUCKET"
                    key = self._add_entity(namespace, event_id, payload.get("summary") or event_id, rel, provenance, canonical, payload.get("type"), payload)
                    self.path_entities[rel] = key
                    self.path_entities[rel.removesuffix(path.suffix)] = key
                    self.records.append((key, payload, rel, canonical, provenance, ""))
                elif rel == "_meta/MEMORY_V2.json":
                    key = self._add_entity("META", "MEMORY_V2", "Memory V2 manifest", rel, "CANONICAL", True, "meta-manifest", payload)
                    self.path_entities[rel] = key
                    self.path_entities[rel.removesuffix(path.suffix)] = key
                    self.records.append((key, payload, rel, True, "CANONICAL", ""))
                continue
            try:
                meta, body = parse_frontmatter(path.read_text(encoding="utf-8"))
            except Exception as exc:
                self.issues.append(GraphIssue("ERROR", "SOURCE_FRONTMATTER_INVALID", str(exc), rel))
                continue
            namespace = _namespace_for_path(rel, meta)
            if namespace is None:
                continue
            stable_id = str(meta.get("id") or path.stem)
            canonical = meta.get("canonical") is not False
            provenance = "CANONICAL" if canonical else "CANONICAL_NONCANONICAL_RECORD"
            key = self._add_entity(
                namespace, stable_id, _label_from_document(path, meta, body, stable_id), rel,
                provenance, canonical, str(meta.get("type")) if meta.get("type") is not None else None, meta,
                aliases=(path.stem, str(meta.get("workstream")) if meta.get("workstream") else None),
            )
            self.path_entities[rel] = key
            self.path_entities[rel.removesuffix(path.suffix)] = key
            self.records.append((key, meta, rel, canonical, provenance, body))

    def _add_entity(
        self,
        namespace: str,
        stable_id: str,
        label: Any,
        source_path: str,
        provenance: str,
        canonical: bool,
        source_type: str | None = None,
        metadata: dict[str, Any] | None = None,
        aliases: Iterable[str | None] = (),
    ) -> str:
        namespace = namespace.upper()
        if namespace not in NAMESPACES:
            self.issues.append(GraphIssue("ERROR", "UNKNOWN_NAMESPACE", f"unsupported namespace {namespace}", source_path))
            return f"{namespace}:{stable_id}"
        stable_id = _normal_text(stable_id)
        key = f"{namespace}:{stable_id}"
        existing = self.entities.get(key)
        if existing is None:
            existing = Entity(
                namespace,
                stable_id,
                _normal_text(label) or stable_id,
                set(),
                provenance,
                canonical,
                source_type,
                {},
                self.link_root,
            )
            self.entities[key] = existing
        elif existing.label == existing.stable_id and label:
            existing.label = _normal_text(label)
        if source_path:
            existing.source_paths.add(source_path)
        if existing.provenance == "GOVERNED_IDENTITY" and provenance != "GOVERNED_IDENTITY":
            existing.provenance = provenance
            existing.canonical = canonical
        if source_type and not existing.source_type:
            existing.source_type = source_type
        if metadata:
            for field_name, value in metadata.items():
                if field_name not in existing.metadata or existing.metadata[field_name] in (None, "", []):
                    existing.metadata[field_name] = _stable_json(value)
        for alias in (stable_id, *aliases):
            if alias in (None, ""):
                continue
            self._add_alias(namespace, str(alias), key, source_path)
        return key

    def _add_alias(self, namespace: str | None, alias: str, key: str, source_path: str) -> None:
        normalized = _normal_text(alias).casefold()
        if not normalized:
            return
        alias_key = (namespace, normalized)
        previous = self.aliases.get(alias_key)
        if previous and previous != key:
            self.issues.append(GraphIssue("ERROR", "NAMESPACE_COLLISION", f"{namespace}:{alias} resolves to both {previous} and {key}", source_path))
            return
        self.aliases[alias_key] = key

    def _runtime_metadata(self, payload: dict[str, Any]) -> dict[str, Any]:
        metadata = dict(payload)
        observed_at = payload.get("observed_at") or payload.get("generated_at")
        if observed_at:
            metadata["freshness"] = _freshness_state(observed_at, self.reference_time)
        return metadata

    def _index_runtime_sources(self) -> None:
        assert self.vault is not None
        live = self.vault / "_live"
        if not live.exists():
            return
        source_files = (
            (live / "SOURCE_OBSERVER.json", "observer"),
            (live / "SOURCE_CANDIDATES.json", "candidate"),
            (live / "BUILDER_HANDOFFS.json", "handoff"),
            (live / "BLOCKERS.json", "blocker"),
        )
        handoff_payload = _json_file(live / "BUILDER_HANDOFFS.json")
        handoff_items = handoff_payload.get("candidates", []) if isinstance(handoff_payload, dict) else []
        try:
            from .observer import _latest_builder_evidence, _valid_handoffs

            valid_handoffs = _valid_handoffs(handoff_items)
            latest_handoffs = _latest_builder_evidence(valid_handoffs)
        except (ImportError, TypeError, ValueError):
            valid_handoffs = []
            latest_handoffs = {}
        latest_ids = {
            int(number): str(item.get("candidate_id"))
            for number, item in latest_handoffs.items()
            if item.get("candidate_id")
        }
        valid_handoff_ids = {str(item.get("candidate_id")) for item in valid_handoffs if item.get("candidate_id")}
        seen_candidates: set[str] = set()
        for path, kind in source_files:
            payload = _json_file(path)
            if not isinstance(payload, dict):
                continue
            rel = f"_live/{path.name}"
            if kind in {"observer", "candidate"}:
                candidates = payload.get("candidates", [])
                if not isinstance(candidates, list):
                    continue
                for candidate in candidates:
                    if not isinstance(candidate, dict) or not candidate.get("candidate_id"):
                        continue
                    cid = str(candidate["candidate_id"])
                    if cid in seen_candidates:
                        continue
                    seen_candidates.add(cid)
                    entity_key = self._add_entity("EVIDENCE", cid, candidate.get("summary") or cid, rel, "RUNTIME_DERIVED", False, candidate.get("candidate_type"), self._runtime_metadata(candidate))
                    self._register_structured_relations(entity_key, candidate, rel, False, "RUNTIME_DERIVED")
                    self._register_runtime_nested(entity_key, candidate, rel)
            elif kind == "handoff":
                candidates = payload.get("candidates", [])
                if not isinstance(candidates, list):
                    continue
                for handoff in candidates:
                    if not isinstance(handoff, dict) or not handoff.get("candidate_id"):
                        continue
                    if str(handoff.get("candidate_id")) not in valid_handoff_ids:
                        continue
                    handoff = dict(handoff)
                    try:
                        builder_number = int(handoff.get("builder_number"))
                    except (TypeError, ValueError):
                        builder_number = None
                    handoff["latest_for_builder"] = bool(builder_number and latest_ids.get(builder_number) == handoff.get("candidate_id"))
                    entity_key = self._add_entity("EVIDENCE", str(handoff["candidate_id"]), f"Builder handoff {handoff.get('builder_number', 'UNKNOWN')}", rel, "RUNTIME_DERIVED", False, handoff.get("candidate_type"), self._runtime_metadata(handoff))
                    self._register_structured_relations(entity_key, handoff, rel, False, "RUNTIME_DERIVED")
                    self._register_runtime_nested(entity_key, handoff, rel)
            else:
                blockers = payload.get("blockers", [])
                if not isinstance(blockers, list):
                    continue
                for blocker in blockers:
                    if not isinstance(blocker, dict) or not blocker.get("blocker_id"):
                        continue
                    entity_key = self._add_entity("BLOCKER", str(blocker["blocker_id"]), blocker.get("summary") or blocker["blocker_id"], rel, "RUNTIME_DERIVED", False, "blocker", self._runtime_metadata(blocker))
                    self._register_structured_relations(entity_key, blocker, rel, False, "RUNTIME_DERIVED")

        for builder_number, handoff in latest_handoffs.items():
            builder = self.entities.get(self._builder_key(builder_number))
            if builder is None:
                continue
            builder.metadata["current_evidence"] = {
                "candidate_id": handoff.get("candidate_id"),
                "role": handoff.get("role"),
                "branch": handoff.get("branch"),
                "head_sha": handoff.get("head_sha"),
                "source_pr": handoff.get("source_pr"),
                "status": handoff.get("status"),
                "blocker_count": len(handoff.get("blockers", [])) if isinstance(handoff.get("blockers"), list) else 0,
                "tests": handoff.get("tests") or handoff.get("tests_passed"),
                "ci": handoff.get("ci"),
                "observed_at": handoff.get("observed_at"),
                "freshness": _freshness_state(handoff.get("observed_at"), self.reference_time),
            }

    def _register_runtime_nested(self, source_key: str, payload: dict[str, Any], source_path: str) -> None:
        blockers = payload.get("blockers")
        if isinstance(blockers, list):
            for blocker in blockers:
                if not isinstance(blocker, dict) or not blocker.get("blocker_id"):
                    continue
                target = self._add_entity("BLOCKER", str(blocker["blocker_id"]), blocker.get("summary") or blocker["blocker_id"], source_path, "RUNTIME_DERIVED", False, "blocker", self._runtime_metadata(blocker))
                self._add_edge(source_key, "blocker", target, source_path, "blockers", str(blocker.get("summary") or blocker["blocker_id"]), "RUNTIME_DERIVED")

    def _register_structured_relations(self, source_key: str, payload: dict[str, Any], source_path: str, canonical: bool, provenance: str) -> None:
        if not isinstance(payload, dict):
            return
        relation_provenance = provenance
        repository = payload.get("source_repository")
        repository_key: str | None = None
        if isinstance(repository, str) and repository.strip():
            repository_key = self._add_entity("REPOSITORY", repository.strip(), repository.strip(), source_path, relation_provenance, canonical, metadata={"repository": repository.strip()})
            self._add_edge(source_key, "source_repository", repository_key, source_path, "source_repository", repository, relation_provenance)
        source_pr = payload.get("source_pr")
        if isinstance(source_pr, int) and not isinstance(source_pr, bool) and source_pr > 0 and repository_key:
            pr_id = f"{str(repository).strip().lower()}#{source_pr}"
            pr_key = self._add_entity("PR", pr_id, f"{repository} PR #{source_pr}", source_path, relation_provenance, canonical, metadata={"repository": repository, "number": source_pr})
            self._add_edge(source_key, "source_pr", pr_key, source_path, "source_pr", str(source_pr), relation_provenance)
        for field_name in ("source_sha", "source_merge_sha", "sha", "frozen_research_sha", "source_latest_meaningful_sha"):
            value = payload.get(field_name)
            if isinstance(value, str) and SHA_RE.fullmatch(value):
                commit_key = self._add_entity("COMMIT", value, f"{value[:12]}…", source_path, relation_provenance, canonical, metadata={"sha": value, "field": field_name})
                self._add_edge(source_key, "merge_commit" if "merge" in field_name else "source_commit", commit_key, source_path, field_name, value, relation_provenance)

        for field_name, (relation, namespace) in FIELD_RELATIONS.items():
            if field_name not in payload:
                continue
            values = payload.get(field_name)
            if isinstance(values, dict):
                values = [values]
            elif not isinstance(values, list):
                values = [values]
            for value in values:
                if isinstance(value, dict):
                    value = value.get("id") or value.get("blocker_id") or value.get("candidate_id")
                if value in (None, "", [], {}):
                    continue
                raw = _normal_text(value)
                if not raw or raw.casefold() in {"none", "n/a", "null", "unknown"}:
                    continue
                if field_name == "evidence":
                    self._register_evidence_value(source_key, raw, source_path, canonical, relation_provenance, payload)
                    continue
                target = self._resolve_target(raw, namespace, source_path, source_key, field_name, canonical, relation_provenance)
                if target:
                    self._add_edge(source_key, relation, target, source_path, field_name, raw, relation_provenance)

        builder_number = payload.get("builder_number")
        builder_value = payload.get("builder")
        builder_match = None
        if isinstance(builder_value, str):
            builder_match = BUILDER_RE.fullmatch(builder_value.strip())
        if builder_match is None and isinstance(builder_number, int) and builder_number in BUILDER_NUMBER_SET:
            builder_match = re.fullmatch(r"([1-5])", str(builder_number))
        if builder_match:
            number = int(builder_match.group(1))
            target = self._builder_key(number)
            self._add_edge(source_key, "builder", target, source_path, "builder_number", str(number), relation_provenance)

        if isinstance(payload.get("domain"), str) and payload["domain"].strip():
            target = self._resolve_target(payload["domain"], "DOMAIN", source_path, source_key, "domain", canonical, relation_provenance, create_referenced=True)
            if target:
                self._add_edge(source_key, "domain", target, source_path, "domain", payload["domain"], relation_provenance)

        for field_name in ("source_merge_sha", "merge_sha"):
            value = payload.get(field_name)
            if isinstance(value, str) and SHA_RE.fullmatch(value):
                target = self._add_entity("COMMIT", value, f"{value[:12]}…", source_path, relation_provenance, canonical, metadata={"sha": value, "field": field_name})
                self._add_edge(source_key, "merge_commit", target, source_path, field_name, value, relation_provenance)

        # Evidence arrays often carry explicit PR, commit, or canonical-record references.
        evidence_values = payload.get("evidence")
        if isinstance(evidence_values, list):
            for raw_value in evidence_values:
                if isinstance(raw_value, str):
                    self._register_evidence_value(source_key, _normal_text(raw_value), source_path, canonical, relation_provenance, payload)

    def _register_evidence_value(self, source_key: str, raw: str, source_path: str, canonical: bool, provenance: str, payload: dict[str, Any]) -> None:
        repo = payload.get("source_repository") if isinstance(payload.get("source_repository"), str) else None
        found = False
        for identifier in ID_RE.findall(raw):
            namespace = ID_NAMESPACE.get(identifier.split("-", 1)[0])
            if namespace:
                target = self._resolve_target(identifier, namespace, source_path, source_key, "evidence", canonical, provenance)
                if target:
                    self._add_edge(source_key, "evidence_reference", target, source_path, "evidence", identifier, provenance)
                found = True
        for sha in SHA_RE.findall(raw):
            target = self._add_entity("COMMIT", sha, f"{sha[:12]}…", source_path, provenance, canonical, metadata={"sha": sha, "field": "evidence"})
            self._add_edge(source_key, "evidence_commit", target, source_path, "evidence", sha, provenance)
            found = True
        pr_match = PR_RE.search(raw)
        if pr_match and repo:
            number = int(pr_match.group(1))
            target = self._add_entity("PR", f"{repo.strip().lower()}#{number}", f"{repo} PR #{number}", source_path, provenance, canonical, metadata={"repository": repo, "number": number})
            self._add_edge(source_key, "evidence_pr", target, source_path, "evidence", f"PR #{number}", provenance)
            found = True
        if not found:
            for possible_path in re.findall(r"\b(?:[A-Za-z0-9_.-]+/)+[A-Za-z0-9_.-]+\.(?:md|json)\b", raw):
                target = self._resolve_path(possible_path)
                if target:
                    self._add_edge(source_key, "evidence_reference", target, source_path, "evidence", possible_path, provenance)
                else:
                    self._record_unresolved(source_path, source_key, "evidence", possible_path, "canonical source path is not indexed")

    def _register_body_links(self, source_key: str, body: str, source_path: str, canonical: bool, provenance: str) -> None:
        for raw_target in WIKILINK_RE.findall(body or ""):
            target_text = _normal_text(raw_target)
            if not target_text:
                continue
            target = self._resolve_path(target_text)
            if target:
                self._add_edge(source_key, "explicit_link", target, source_path, "body", target_text, provenance)
            elif target_text.startswith(("http://", "https://")):
                continue
            else:
                self._record_unresolved(source_path, source_key, "body_link", target_text, "authored wikilink target is not indexed")

    def _resolve_path(self, raw_path: str) -> str | None:
        cleaned = raw_path.strip().lstrip("/")
        candidates = [cleaned, cleaned.removesuffix(".md"), cleaned.removesuffix(".json")]
        for candidate in candidates:
            if candidate in self.path_entities:
                return self.path_entities[candidate]
        return None

    def _builder_key(self, number: int) -> str:
        return f"BUILDER:BUILDER-{number}"

    def _resolve_target(
        self,
        raw: str,
        namespace: str | None,
        source_path: str,
        source_key: str,
        field_name: str,
        canonical: bool,
        provenance: str,
        *,
        create_referenced: bool = False,
    ) -> str | None:
        raw = _normal_text(raw)
        if namespace:
            namespace = namespace.upper()
        if raw.startswith("BUILDER:") and raw in self.entities:
            return raw
        if namespace == "PR" and re.fullmatch(r"\d+", raw):
            self._record_unresolved(source_path, source_key, field_name, raw, "PR number requires source_repository")
            return None
        candidates: list[str] = []
        if namespace:
            candidates.append(self.aliases.get((namespace, raw.casefold()), ""))
        inferred = ID_NAMESPACE.get(raw.split("-", 1)[0]) if "-" in raw else None
        if inferred:
            candidates.append(self.aliases.get((inferred, raw.casefold()), ""))
        for candidate in candidates:
            if candidate:
                return candidate
        if namespace in {"WORKSTREAM", "INVARIANT", "DOMAIN", "PROVIDER", "MODEL", "DATASET", "REPOSITORY"} or create_referenced:
            if namespace is None:
                return None
            return self._add_entity(namespace, raw, raw, source_path, "CANONICAL_REFERENCE" if canonical else "RUNTIME_DERIVED", canonical)
        if namespace == "BUILDER":
            match = re.fullmatch(r"(?:Builder\s*)?([1-5])", raw, re.IGNORECASE)
            if match:
                return self._builder_key(int(match.group(1)))
        if inferred and inferred in self.entities:
            return self.aliases.get((inferred, raw.casefold()))
        self._record_unresolved(source_path, source_key, field_name, raw, "explicit target has no authoritative entity")
        return None

    def _record_unresolved(self, source_path: str, source_key: str, relation: str, raw_target: str, reason: str) -> None:
        item = {
            "source_file": source_path,
            "source_entity": source_key,
            "field_relation": relation,
            "raw_target": raw_target,
            "reason": reason,
        }
        if item not in self.unresolved:
            self.unresolved.append(item)

    def _add_edge(self, source: str, relation: str, target: str, source_path: str, field_name: str, raw_target: str, provenance: str) -> None:
        if source == target:
            self.issues.append(GraphIssue("ERROR", "SELF_LINK", f"self-link is not allowed: {source} {relation}", source_path))
            return
        if source not in self.entities or target not in self.entities:
            self.issues.append(GraphIssue("ERROR", "DANGLING_EDGE", f"edge references missing entity: {source} -> {target}", source_path))
            return
        edge_key = (source, relation, target)
        existing = self.edges.get(edge_key)
        evidence = {"path": source_path, "field": field_name}
        if existing is None:
            self.edges[edge_key] = GraphEdge(source, relation, target, source_path, field_name, raw_target, provenance, [evidence])
        elif evidence not in existing.evidence:
            existing.evidence.append(evidence)

    def health(self) -> dict[str, Any]:
        entities = sorted(self.entities.values(), key=lambda entity: entity.key)
        edges = sorted(self.edges.values(), key=lambda edge: (edge.source, edge.relation, edge.target))
        adjacency: dict[str, set[str]] = {entity.key: set() for entity in entities}
        for edge in edges:
            adjacency[edge.source].add(edge.target)
            adjacency[edge.target].add(edge.source)
        seen: set[str] = set()
        component_sizes: list[int] = []
        for key in sorted(adjacency):
            if key in seen:
                continue
            queue = [key]
            seen.add(key)
            size = 0
            while queue:
                current = queue.pop()
                size += 1
                for target in sorted(adjacency[current]):
                    if target not in seen:
                        seen.add(target)
                        queue.append(target)
            component_sizes.append(size)
        isolated = sum(1 for key, neighbors in adjacency.items() if not neighbors)
        relation_counts = Counter(edge.relation for edge in edges)
        type_counts = Counter(entity.namespace for entity in entities)
        degrees = Counter()
        for edge in edges:
            degrees[edge.source] += 1
            degrees[edge.target] += 1
        top_hubs = [
            {"entity_key": key, "label": self.entities[key].label, "degree": degree}
            for key, degree in sorted(degrees.items(), key=lambda item: (-item[1], item[0]))[:20]
        ]
        after = {
            "entity_count": len(entities),
            "graph_nodes": len(entities),
            "edge_count": len(edges),
            "isolated_node_count": isolated,
            "isolated_node_percent": round((isolated / len(entities) * 100.0), 2) if entities else 0.0,
            "connected_components": len(component_sizes),
            "largest_component": max(component_sizes, default=0),
            "unresolved_reference_count": len(self.unresolved),
            "dangling_wikilink_count": 0,
            "edges_by_relation": dict(sorted(relation_counts.items())),
            "node_types": dict(sorted(type_counts.items())),
            "top_hubs": top_hubs,
        }
        baseline_nodes = len(entities)
        baseline = {
            "definition": "canonical entity index before Semantic Graph V2 link materialization",
            "entity_count": baseline_nodes,
            "graph_nodes": baseline_nodes,
            "edge_count": 0,
            "isolated_node_count": baseline_nodes,
            "isolated_node_percent": 100.0 if baseline_nodes else 0.0,
            "connected_components": baseline_nodes,
            "largest_component": 1 if baseline_nodes else 0,
        }
        return {"baseline": baseline, "after": after}

    def semantic_payload(self) -> dict[str, Any]:
        return {
            "schema": GRAPH_SCHEMA,
            "canonical_input_digest": canonical_input_digest(self.root),
            "canonical_event_digest": canonical_event_digest(self.root),
            "entities": [self.entities[key].as_dict() for key in sorted(self.entities)],
            "edges": [self.edges[key].as_dict() for key in sorted(self.edges)],
            "unresolved_references": sorted(self.unresolved, key=lambda item: tuple(item.values())),
        }

    def digest(self) -> str:
        encoded = json.dumps(_stable_json(self.semantic_payload()), sort_keys=True, separators=(",", ":"), ensure_ascii=True)
        return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def _link(entity: Entity, label: str | None = None) -> str:
    return f"[[{entity.target}|{label or entity.label}]]"


def _render_entity_page(graph: SemanticGraph, entity: Entity, incoming: dict[str, list[GraphEdge]]) -> str:
    outgoing = [edge for edge in graph.edges.values() if edge.source == entity.key]
    outgoing.sort(key=lambda edge: (edge.relation, edge.target))
    back = sorted(incoming.get(entity.key, []), key=lambda edge: (edge.source, edge.relation))
    lines = [GRAPH_MARKER, "---", "graph_generated: true", "graph_noncanonical: true", f"namespace: {entity.namespace}", f"stable_id: {entity.stable_id}", f"canonical: {str(entity.canonical).lower()}", "---", f"# {entity.label}", "", f"- Entity: `{entity.key}`", f"- Provenance: `{entity.provenance}`", f"- Source paths: {', '.join(f'`{path}`' for path in sorted(entity.source_paths)) or '`none`'}"]
    if entity.metadata:
        lines.extend(["", "## Evidence-derived metadata", ""])
        for key, value in sorted(entity.metadata.items()):
            rendered = json.dumps(value, ensure_ascii=False, sort_keys=True) if isinstance(value, (dict, list)) else str(value)
            lines.append(f"- `{key}`: {rendered}")
    lines.extend(["", "## Typed relations", ""])
    if outgoing:
        for edge in outgoing:
            target = graph.entities[edge.target]
            lines.append(f"- `{edge.relation}` → {_link(target)}")
    else:
        lines.append("- None recorded from authoritative structured fields or explicit links.")
    lines.extend(["", "## Typed backlinks", ""])
    if back:
        for edge in back:
            source = graph.entities[edge.source]
            lines.append(f"- `{edge.relation}` ← {_link(source)}")
    else:
        lines.append("- None recorded.")
    return "\n".join(lines).rstrip() + "\n"


def _render_moc(title: str, description: str, entities: Iterable[Entity]) -> str:
    selected = sorted(entities, key=lambda entity: entity.key)
    lines = [GRAPH_MARKER, f"# {title}", "", description, "", f"- Entity count: **{len(selected)}**", ""]
    if selected:
        lines.extend(f"- {_link(entity)} — `{entity.namespace}`" for entity in selected)
    else:
        lines.append("- No authoritative entities currently resolve to this hub.")
    return "\n".join(lines).rstrip() + "\n"


def _render_builder_moc(entities: Iterable[Entity]) -> str:
    selected = sorted(entities, key=lambda entity: entity.key)
    lines = [
        GRAPH_MARKER,
        "# Builders Graph MOC",
        "",
        "Builder identities are governed as 1–5; role and status remain evidence-derived.",
        "",
        f"- Entity count: **{len(selected)}**",
        "",
    ]
    for entity in selected:
        lines.append(f"- {_link(entity)} — `{entity.namespace}`")
        current = entity.metadata.get("current_evidence")
        if not isinstance(current, dict):
            lines.append("  - current evidence: **UNKNOWN / NO CURRENT HANDOFF EVIDENCE**")
            continue
        freshness = current.get("freshness") or "STALE"
        lines.extend([
            f"  - current evidence: `{current.get('candidate_id') or 'UNKNOWN'}`",
            f"  - current role: {current.get('role') or 'UNKNOWN'}",
            f"  - current branch: {current.get('branch') or 'UNKNOWN'}",
            f"  - current head SHA: `{current.get('head_sha') or 'UNKNOWN'}`",
            f"  - current PR: {('PR #' + str(current['source_pr'])) if current.get('source_pr') else 'UNKNOWN'}",
            f"  - current status: {current.get('status') or 'UNKNOWN'}",
            f"  - current blocker count: {current.get('blocker_count', 0)}",
            f"  - current tests/CI: {current.get('tests') or 'UNKNOWN'} / {current.get('ci') or 'UNKNOWN'}",
            f"  - observed_at: `{current.get('observed_at') or 'UNKNOWN'}`",
            f"  - freshness: **{freshness}**" + (" — not unquestionably current; CEO review required." if freshness == "STALE" else ""),
        ])
    return "\n".join(lines).rstrip() + "\n"


def render_semantic_graph(graph: SemanticGraph, output_root: Path | None = None) -> dict[str, Any]:
    if output_root is not None:
        graph.configure_output(output_root)
    output = graph.output_root
    entities_root = output / "entities"
    output.mkdir(parents=True, exist_ok=True)
    entities_root.mkdir(parents=True, exist_ok=True)
    for stale in sorted(entities_root.rglob("*"), reverse=True):
        if stale.is_file():
            # Entity pages are always Markdown; clear stale pages from an older
            # projection version before materializing the current registry.
            stale.unlink()
    incoming: dict[str, list[GraphEdge]] = defaultdict(list)
    for edge in graph.edges.values():
        incoming[edge.target].append(edge)
    for entity in sorted(graph.entities.values(), key=lambda item: item.key):
        path = output / "entities" / entity.namespace / f"{_safe_slug(entity.stable_id)}.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(_render_entity_page(graph, entity, incoming), encoding="utf-8")

    health = graph.health()
    by_namespace = defaultdict(list)
    for entity in graph.entities.values():
        by_namespace[entity.namespace].append(entity)
    workstream_keys = {key for key, entity in graph.entities.items() if entity.namespace == "WORKSTREAM" and "TOP5" in entity.stable_id.upper()}
    top5_keys = set(workstream_keys)
    for edge in graph.edges.values():
        if edge.source in workstream_keys:
            top5_keys.add(edge.target)
        if edge.target in workstream_keys:
            top5_keys.add(edge.source)
    moc_specs = {
        "MOC-TOP5.md": ("Top-5 Graph MOC", "Only entities connected by explicit Top-5 workstream relations are listed.", [graph.entities[key] for key in sorted(top5_keys) if key in graph.entities]),
        "MOC-BUILDERS.md": ("Builders Graph MOC", "Builder identities are governed as 1–5; role and status remain evidence-derived.", by_namespace["BUILDER"]),
        "MOC-PROVIDERS.md": ("Providers Graph MOC", "Providers appear only from canonical structured fields, records, or runtime evidence.", by_namespace["PROVIDER"]),
        "MOC-MODELS.md": ("Models Graph MOC", "Models appear only from canonical structured fields or records.", by_namespace["MODEL"]),
        "MOC-WORKSTREAMS.md": ("Workstreams Graph MOC", "Workstreams are linked from explicit structured workstream fields and authored links.", by_namespace["WORKSTREAM"]),
        "MOC-DECISIONS.md": ("Decisions Graph MOC", "Decisions are linked from canonical decision records and explicit references.", by_namespace["DECISION"]),
        "MOC-BLOCKERS.md": ("Blockers Graph MOC", "Blockers are runtime-derived only when present in observer evidence; no blocker is fabricated by the graph.", by_namespace["BLOCKER"]),
    }
    for filename, (title, description, items) in moc_specs.items():
        rendered = _render_builder_moc(items) if filename == "MOC-BUILDERS.md" else _render_moc(title, description, items)
        (output / filename).write_text(rendered, encoding="utf-8")

    activity = []
    for entity in graph.entities.values():
        stamp = entity.metadata.get("timestamp") or entity.metadata.get("observed_at") or entity.metadata.get("last_updated")
        parsed = _parse_time(stamp)
        if parsed and entity.namespace in {"EVENT", "EVIDENCE", "FINDING", "VERIFICATION", "DECISION", "TASK"}:
            activity.append((parsed, entity))
    activity.sort(key=lambda item: (item[0], item[1].key), reverse=True)
    (output / "MOC-RECENT-ACTIVITY.md").write_text(_render_moc("Recent Activity Graph MOC", "Newest timestamped events and operational evidence, sorted deterministically.", [item[1] for item in activity[:40]]), encoding="utf-8")

    health_payload = {
        "schema": GRAPH_SCHEMA,
        "graph_version": "semantic-link-graph-v2",
        "graph_digest": graph.digest(),
        "generated_at": graph.generated_at,
        "baseline": health["baseline"],
        "after": health["after"],
        "unresolved_references": sorted(graph.unresolved, key=lambda item: tuple(item.values())),
    }
    (output / "GRAPH_HEALTH.json").write_text(json.dumps(health_payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    health_lines = [
        GRAPH_MARKER, "# Semantic Graph V2 Health", "", f"- Graph digest: `{graph.digest()}`",
        f"- Runtime included: **{str(graph.include_runtime).lower()}**", "", "## Baseline", "",
    ]
    health_lines.extend(f"- {key.replace('_', ' ').title()}: **{value}**" for key, value in sorted(health["baseline"].items()))
    health_lines.extend(["", "## Generated graph", ""])
    health_lines.extend(f"- {key.replace('_', ' ').title()}: **{value}**" for key, value in sorted(health["after"].items()) if key not in {"edges_by_relation", "node_types", "top_hubs"})
    health_lines.extend(["", "### Edges by relation", ""])
    health_lines.extend(f"- `{key}`: **{value}**" for key, value in sorted(health["after"]["edges_by_relation"].items()))
    health_lines.extend(["", "### Node types", ""])
    health_lines.extend(f"- `{key}`: **{value}**" for key, value in sorted(health["after"]["node_types"].items()))
    (output / "GRAPH_HEALTH.md").write_text("\n".join(health_lines).rstrip() + "\n", encoding="utf-8")
    (output / "UNRESOLVED_REFERENCES.json").write_text(json.dumps({"schema": GRAPH_SCHEMA, "references": health_payload["unresolved_references"]}, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    unresolved_lines = [GRAPH_MARKER, "# Unresolved Semantic Graph References", "", "These references were explicit but did not resolve to an authoritative entity. No broken wikilink was emitted.", ""]
    if graph.unresolved:
        unresolved_lines.extend(f"- `{item['source_file']}` / `{item['source_entity']}` / `{item['field_relation']}` → `{item['raw_target']}` — {item['reason']}" for item in health_payload["unresolved_references"])
    else:
        unresolved_lines.append("- None.")
    (output / "UNRESOLVED_REFERENCES.md").write_text("\n".join(unresolved_lines).rstrip() + "\n", encoding="utf-8")

    manifest_payload = graph.semantic_payload()
    manifest = {
        "schema": GRAPH_SCHEMA,
        "graph_version": "semantic-link-graph-v2",
        "generated_at": graph.generated_at,
        "graph_digest": graph.digest(),
        "canonical_input_digest": manifest_payload["canonical_input_digest"],
        "canonical_event_digest": manifest_payload["canonical_event_digest"],
        "generated_location": graph.link_root,
        "noncanonical_view": True,
        "runtime_included": graph.include_runtime,
        "namespaces": list(NAMESPACES),
        "relation_count": len(graph.edges),
        "entity_count": len(graph.entities),
        "entities": manifest_payload["entities"],
        "edges": manifest_payload["edges"],
        "unresolved_references": manifest_payload["unresolved_references"],
        "health": health,
        "architecture_contract": {
            "canonical_history": "append-only and read-only to this projection",
            "candidate_semantics": "canonical=false and promotion_required=true remain runtime-derived",
            "wikilinks": "generated only to resolvable graph entity pages",
            "backlinks": "derived from typed outgoing edges",
        },
    }
    (output / "GRAPH_MANIFEST.json").write_text(json.dumps(_stable_json(manifest), indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")
    (output / "README.md").write_text(
        "\n".join([
            GRAPH_MARKER, "# Memory Semantic Link Graph V2", "",
            "Generated noncanonical view layer. Build with `python3 tools/memory.py graph build`; validate with `python3 tools/memory.py graph validate`.",
            "", "Canonical records are read-only inputs. Runtime `_live` records are included only when an explicit vault is supplied and remain `canonical: false`.",
            f"", f"Projection location: `{graph.link_root}`.",
            "", "The semantic digest excludes generated timestamps and performance measurements.", "",
        ]), encoding="utf-8"
    )
    home_lines = [GRAPH_MARKER, "# Memory Semantic Link Graph V2", "", "This is a deterministic, noncanonical derived view over canonical Memory records and, when explicitly requested, a read-only `_live` observer snapshot.", "", "## Safety boundary", "", "- Canonical events/history are read-only inputs.", "- Runtime candidates, operational handoffs, and blockers remain noncanonical and promotion-gated.", "- NO-BET, no live activation, and SEALED 2425/2526 remain source invariants; this graph cannot promote or resolve them.", "- Remove the selected projection root to roll back the view without rewriting canonical Memory.", "", "## Health", "", f"- Graph digest: `{graph.digest()}`", f"- Entities: **{health['after']['entity_count']}**", f"- Typed edges: **{health['after']['edge_count']}**", f"- Isolated nodes: **{health['after']['isolated_node_count']}** ({health['after']['isolated_node_percent']}%)", f"- Connected components: **{health['after']['connected_components']}**; largest: **{health['after']['largest_component']}**", f"- Unresolved references: **{health['after']['unresolved_reference_count']}**", "", "## Hubs", ""]
    home_lines.extend(f"- [[{graph.link_root}/{filename.removesuffix('.md')}|{title}]]" for filename, (title, _, _) in moc_specs.items())
    home_lines.append(f"- [[{graph.link_root}/MOC-RECENT-ACTIVITY|Recent Activity Graph MOC]]")
    (output / "00_GRAPH_HOME.md").write_text("\n".join(home_lines).rstrip() + "\n", encoding="utf-8")
    return {"output": str(output), "graph_digest": graph.digest(), "build_seconds": graph.build_seconds, "health": health, "entity_count": len(graph.entities), "edge_count": len(graph.edges), "unresolved_count": len(graph.unresolved)}


def build_semantic_graph(
    root: Path,
    *,
    vault: Path | None = None,
    include_runtime: bool = False,
    output_root: Path | None = None,
    link_root: str | None = None,
    reference_time: str | None = None,
) -> dict[str, Any]:
    if include_runtime and vault is not None and output_root is None:
        return build_semantic_graph_atomic(root, vault, reference_time=reference_time)
    graph = SemanticGraph(
        root,
        vault=vault,
        include_runtime=include_runtime,
        output_root=output_root,
        link_root=link_root,
        reference_time=reference_time,
    ).build()
    return render_semantic_graph(graph)


def _write_json_atomic(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as handle:
        json.dump(payload, handle, indent=2, sort_keys=True, ensure_ascii=False)
        handle.write("\n")
        temporary = Path(handle.name)
    temporary.replace(path)


def _runtime_graph_status(vault: Path, payload: dict[str, Any]) -> None:
    _write_json_atomic(vault / "_live" / "SEMANTIC_GRAPH_STATUS.json", payload)


class SemanticGraphRuntimeError(RuntimeError):
    """A runtime graph could not be validated and promoted safely."""


def _remove_runtime_path(path: Path) -> None:
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    elif path.exists() or path.is_symlink():
        path.unlink()


def build_semantic_graph_atomic(
    root: Path,
    vault: Path,
    *,
    reference_time: str | None = None,
) -> dict[str, Any]:
    """Build, validate, and atomically promote the current Vault graph.

    The temporary directory is a sibling of the live graph so promotion is a
    same-filesystem rename.  The previous graph is retained until the new
    graph has passed validation, and is restored if the final rename fails.
    """
    root = root.resolve()
    vault = vault.resolve()
    live = vault / "_live"
    live.mkdir(parents=True, exist_ok=True)
    current = live / "graph"
    temporary: Path | None = Path(tempfile.mkdtemp(prefix=".graph-build-", dir=live))
    previous: Path | None = None
    try:
        graph = SemanticGraph(
            root,
            vault=vault,
            include_runtime=True,
            output_root=temporary,
            link_root="_live/graph",
            reference_time=reference_time,
        ).build()
        result = render_semantic_graph(graph)
        validation = validate_semantic_graph(root, temporary, vault=vault, link_base=vault)
        result["validation"] = validation.to_dict()
        if validation.errors or validation.warnings:
            raise SemanticGraphRuntimeError(
                f"GRAPH VALIDATION FAILED: errors={validation.errors} warnings={validation.warnings}"
            )

        if current.exists():
            previous = Path(tempfile.mkdtemp(prefix=".graph-previous-", dir=live))
            previous.rmdir()
            os.replace(current, previous)
        try:
            os.replace(temporary, current)
            temporary = None
        except Exception:
            if previous is not None and not current.exists():
                os.replace(previous, current)
                previous = None
            raise
        result["output"] = str(current)
        if previous is not None:
            _remove_runtime_path(previous)
            previous = None
        _runtime_graph_status(vault, {
            "schema": 1,
            "status": "ONLINE",
            "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
            "graph_root": "_live/graph",
            "graph_digest": result["graph_digest"],
            "canonical_input_digest": graph.semantic_payload()["canonical_input_digest"],
            "runtime_included": True,
            "last_good_graph": True,
            "validation": {"errors": 0, "warnings": 0},
        })
        return result
    except Exception as exc:
        if previous is not None and not current.exists():
            os.replace(previous, current)
            previous = None
        if temporary is not None and temporary.exists():
            shutil.rmtree(temporary, ignore_errors=True)
        try:
            _runtime_graph_status(vault, {
                "schema": 1,
                "status": "DEGRADED",
                "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
                "graph_root": "_live/graph",
                "last_good_graph": current.exists(),
                "error": str(exc),
                "failure": "new graph was not promoted; previous valid graph was preserved",
            })
        except OSError:
            pass
        if isinstance(exc, SemanticGraphRuntimeError):
            raise
        raise SemanticGraphRuntimeError(f"GRAPH GENERATION FAILED: {exc}") from exc
    finally:
        if previous is not None and previous.exists():
            try:
                _remove_runtime_path(previous)
            except OSError:
                pass
        if temporary is not None and temporary.exists():
            shutil.rmtree(temporary, ignore_errors=True)


def _read_manifest(graph_root: Path) -> dict[str, Any] | None:
    path = graph_root / "GRAPH_MANIFEST.json"
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _display_path(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return str(path)


def _link_target_path(target: str, link_base: Path, graph_root: Path | None = None, graph_location: str | None = None) -> Path:
    normalized = target.strip().strip("/")
    location = (graph_location or "").strip().strip("/")
    if graph_root is not None and location and (normalized == location or normalized.startswith(location + "/")):
        relative = normalized[len(location):].lstrip("/")
        return (graph_root / (relative if relative.endswith(".md") else f"{relative}.md")).resolve()
    return (link_base / (normalized if normalized.endswith(".md") else f"{normalized}.md")).resolve()


def validate_semantic_graph(
    root: Path,
    graph_root: Path | None = None,
    *,
    vault: Path | None = None,
    link_base: Path | None = None,
) -> GraphValidation:
    root = root.resolve()
    vault = vault.resolve() if vault else None
    graph_root = (graph_root or ((vault / "_live" / "graph") if vault else (root / GRAPH_RELATIVE_ROOT))).resolve()
    link_base = (link_base or vault or root).resolve()
    issues: list[GraphIssue] = []
    manifest = _read_manifest(graph_root)
    if manifest is None:
        return GraphValidation(1, 0, [GraphIssue("ERROR", "GRAPH_MANIFEST_MISSING", "GRAPH_MANIFEST.json is missing or invalid", str(graph_root))], {})
    if manifest.get("schema") != GRAPH_SCHEMA:
        issues.append(GraphIssue("ERROR", "GRAPH_SCHEMA", f"expected graph schema {GRAPH_SCHEMA}", "GRAPH_MANIFEST.json"))
    if manifest.get("noncanonical_view") is not True:
        issues.append(GraphIssue("ERROR", "GRAPH_CANONICAL_FLAG", "graph projection must be explicitly noncanonical", "GRAPH_MANIFEST.json"))
    if manifest.get("runtime_included") and vault is None:
        issues.append(GraphIssue("ERROR", "RUNTIME_LINK_BASE_MISSING", "runtime graph validation requires the Vault as link base", "GRAPH_MANIFEST.json"))
    graph_location = manifest.get("generated_location") if isinstance(manifest.get("generated_location"), str) else GRAPH_RELATIVE_ROOT
    expected_input = canonical_input_digest(root)
    if manifest.get("canonical_input_digest") != expected_input:
        issues.append(GraphIssue("ERROR", "CANONICAL_INPUT_MUTATED", "canonical input digest differs from graph manifest; rebuild the current graph before validation", "GRAPH_MANIFEST.json"))
    expected_events = canonical_event_digest(root)
    if manifest.get("canonical_event_digest") != expected_events:
        issues.append(GraphIssue("ERROR", "CANONICAL_EVENTS_MUTATED", "canonical event digest differs from graph manifest; rebuild the current graph before validation", "GRAPH_MANIFEST.json"))
    entities = manifest.get("entities")
    edges = manifest.get("edges")
    if not isinstance(entities, list) or not isinstance(edges, list):
        issues.append(GraphIssue("ERROR", "GRAPH_MANIFEST_SHAPE", "entities and edges must be lists", "GRAPH_MANIFEST.json"))
        return GraphValidation(sum(1 for issue in issues if issue.severity == "ERROR"), 0, issues, {})
    entity_keys = [item.get("entity_key") for item in entities if isinstance(item, dict)]
    if len(entity_keys) != len(set(entity_keys)):
        issues.append(GraphIssue("ERROR", "DUPLICATE_ENTITIES", "duplicate entity keys in manifest", "GRAPH_MANIFEST.json"))
    edge_keys = [(item.get("source"), item.get("relation"), item.get("target")) for item in edges if isinstance(item, dict)]
    if len(edge_keys) != len(set(edge_keys)):
        issues.append(GraphIssue("ERROR", "DUPLICATE_EDGES", "duplicate typed edges in manifest", "GRAPH_MANIFEST.json"))
    entity_set = set(entity_keys)
    for entity in entities:
        if not isinstance(entity, dict):
            issues.append(GraphIssue("ERROR", "ENTITY_SHAPE", "entity is not an object", "GRAPH_MANIFEST.json"))
            continue
        key = entity.get("entity_key")
        target = entity.get("target")
        if key not in entity_set or not isinstance(target, str):
            issues.append(GraphIssue("ERROR", "ENTITY_TARGET", "entity target is missing", "GRAPH_MANIFEST.json"))
            continue
        path = _link_target_path(target, link_base, graph_root, graph_location)
        if not path.exists():
            issues.append(GraphIssue("ERROR", "MISSING_ENTITY_PAGE", f"generated entity page missing for {key}", target))
        try:
            path.relative_to(graph_root)
        except ValueError:
            issues.append(GraphIssue("ERROR", "ENTITY_TARGET_OUTSIDE_GRAPH", f"entity target for {key} is outside selected graph root", target))
        if not isinstance(key, str) or ":" not in key or key.split(":", 1)[0] not in NAMESPACES:
            issues.append(GraphIssue("ERROR", "UNKNOWN_NAMESPACE", f"entity uses unsupported namespace: {key}", "GRAPH_MANIFEST.json"))
    for edge in edges:
        if not isinstance(edge, dict):
            issues.append(GraphIssue("ERROR", "EDGE_SHAPE", "edge is not an object", "GRAPH_MANIFEST.json"))
            continue
        if edge.get("source") not in entity_set or edge.get("target") not in entity_set:
            issues.append(GraphIssue("ERROR", "DANGLING_EDGE", "edge source or target is absent from entity registry", "GRAPH_MANIFEST.json"))
        if edge.get("source") == edge.get("target"):
            issues.append(GraphIssue("ERROR", "SELF_LINK", "self-link is not allowed", "GRAPH_MANIFEST.json"))
    link_pattern = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")
    for path in sorted(graph_root.rglob("*.md")) if graph_root.exists() else []:
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            issues.append(GraphIssue("ERROR", "GRAPH_READ", str(exc), _display_path(path, root)))
            continue
        for target in link_pattern.findall(text):
            target = target.strip()
            if target.startswith(("http://", "https://")):
                continue
            target_path = _link_target_path(target, link_base, graph_root, graph_location)
            if not target_path.exists():
                issues.append(GraphIssue("ERROR", "DANGLING_WIKILINK", f"generated wikilink target does not exist: {target}", _display_path(path, root)))
    semantic = {
        "schema": manifest.get("schema"),
        "canonical_input_digest": manifest.get("canonical_input_digest"),
        "canonical_event_digest": manifest.get("canonical_event_digest"),
        "entities": entities,
        "edges": edges,
        "unresolved_references": manifest.get("unresolved_references", []),
    }
    expected_graph_digest = hashlib.sha256(json.dumps(_stable_json(semantic), sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("utf-8")).hexdigest()
    if manifest.get("graph_digest") != expected_graph_digest:
        issues.append(GraphIssue("ERROR", "GRAPH_DIGEST", "semantic graph digest is not reproducible", "GRAPH_MANIFEST.json"))
    unresolved = manifest.get("unresolved_references", [])
    if not isinstance(unresolved, list):
        issues.append(GraphIssue("ERROR", "UNRESOLVED_SHAPE", "unresolved_references must be a list", "GRAPH_MANIFEST.json"))
        unresolved = []
    report_health = manifest.get("health", {}).get("after", {}) if isinstance(manifest.get("health"), dict) else {}
    graph = SemanticGraph(root, vault=vault, include_runtime=bool(manifest.get("runtime_included")), output_root=graph_root, link_root=manifest.get("generated_location") or GRAPH_RELATIVE_ROOT)
    for entity in entities:
        if isinstance(entity, dict) and isinstance(entity.get("entity_key"), str) and ":" in entity["entity_key"]:
            namespace, stable_id = entity["entity_key"].split(":", 1)
            target = str(entity.get("target") or GRAPH_RELATIVE_ROOT)
            target_root = target.split("/entities/", 1)[0] if "/entities/" in target else graph.link_root
            graph.entities[entity["entity_key"]] = Entity(namespace, stable_id, entity.get("label", stable_id), set(entity.get("source_paths", [])), entity.get("provenance", "UNKNOWN"), bool(entity.get("canonical")), entity.get("source_type"), entity.get("metadata", {}), target_root)
    for edge in edges:
        if isinstance(edge, dict) and all(edge.get(key) for key in ("source", "relation", "target")):
            graph.edges[(edge["source"], edge["relation"], edge["target"])] = GraphEdge(edge["source"], edge["relation"], edge["target"], edge.get("source_path", ""), edge.get("field", ""), edge.get("raw_target", ""), edge.get("provenance", ""), edge.get("evidence", []))
    graph.unresolved = list(unresolved)
    computed = graph.health()["after"]
    for key in ("entity_count", "graph_nodes", "edge_count", "isolated_node_count", "connected_components", "largest_component", "unresolved_reference_count"):
        if report_health.get(key) != computed.get(key):
            issues.append(GraphIssue("ERROR", "HEALTH_DRIFT", f"health field {key} differs from generated graph", "GRAPH_MANIFEST.json"))
    error_count = sum(1 for issue in issues if issue.severity in {"ERROR", "FATAL"})
    warning_count = sum(1 for issue in issues if issue.severity == "WARNING")
    return GraphValidation(error_count, warning_count, issues, {"baseline": manifest.get("health", {}).get("baseline", {}), "after": computed, "unresolved_references": unresolved})


def semantic_graph_health(root: Path, graph_root: Path | None = None, *, vault: Path | None = None) -> dict[str, Any]:
    validation = validate_semantic_graph(root, graph_root, vault=vault)
    return {"errors": validation.errors, "warnings": validation.warnings, "health": validation.health}
