"""SportsBrain Memory V2 event, projection, and context-packet primitives."""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re
import tempfile
from typing import Any

EVENT_TYPES = {
    "CEO_DECISION", "PR_MERGED", "WORKSTREAM_STARTED", "WORKSTREAM_COMPLETED",
    "RESEARCH_GATE", "PRODUCTION_VERIFIED", "BLOCKER_OPENED", "BLOCKER_RESOLVED",
    "ARCHITECTURE_CHANGED", "ROLLBACK", "DEFERRED_DEPENDENCY",
}
VERIFIED_STATES = {"ceo_approved", "independently_verified", "merged_source"}
PENDING_STATES = {"builder_report", "pending", "unresolved"}
EVENT_ID_RE = re.compile(r"EVT-\d{8}-\d{3,}")
SHA_RE = re.compile(r"^[0-9a-f]{40}$")
SECRET_PATTERNS = (
    re.compile(r"\bsk-[A-Za-z0-9]{20,}\b"),
    re.compile(r"\bgh[pousr]_[A-Za-z0-9]{20,}\b"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(r"(?i)bearer\s+[A-Za-z0-9._-]{24,}"),
)
V1_GENERATED_MARKER = "<!-- GENERATED BY SportsBrainMemory V1: DO NOT EDIT -->"
V2_GENERATED_MARKER = "<!-- GENERATED BY SportsBrainMemory V2: DO NOT EDIT -->"


class MemoryV2Error(ValueError):
    """Raised when an update cannot be accepted without guessing."""


@dataclass(frozen=True)
class IngestResult:
    event_id: str
    destination: str
    changed: bool


def now_utc() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def parse_timestamp(value: Any, field: str = "timestamp") -> datetime:
    if not isinstance(value, str) or not value.strip():
        raise MemoryV2Error(f"{field} must be an ISO-8601 timestamp")
    try:
        parsed = datetime.fromisoformat(value.strip().replace("Z", "+00:00"))
    except ValueError as exc:
        raise MemoryV2Error(f"{field} is not a valid ISO-8601 timestamp: {value!r}") from exc
    if parsed.tzinfo is None:
        raise MemoryV2Error(f"{field} must include a timezone: {value!r}")
    return parsed.astimezone(timezone.utc)


def _scan_for_secrets(value: Any, path: str = "event") -> None:
    if isinstance(value, dict):
        for key, child in value.items():
            _scan_for_secrets(child, f"{path}.{key}")
    elif isinstance(value, list):
        for index, child in enumerate(value):
            _scan_for_secrets(child, f"{path}[{index}]")
    elif isinstance(value, str) and any(pattern.search(value) for pattern in SECRET_PATTERNS):
        raise MemoryV2Error(f"secret-like material detected at {path}")


def validate_event(event: dict[str, Any], *, canonical: bool | None = None) -> dict[str, Any]:
    if not isinstance(event, dict):
        raise MemoryV2Error("event must be an object")
    required = {
        "event_id", "timestamp", "type", "domain", "summary", "source_repository",
        "builder", "ceo_gate_state", "affected_workstreams", "findings", "invariants",
        "supersedes", "evidence", "verification_state",
    }
    missing = sorted(required - set(event))
    if missing:
        raise MemoryV2Error(f"event missing required field(s): {', '.join(missing)}")
    event_id = event["event_id"]
    if not isinstance(event_id, str) or not EVENT_ID_RE.fullmatch(event_id):
        raise MemoryV2Error(f"event_id must match EVT-YYYYMMDD-NNN: {event_id!r}")
    parse_timestamp(event["timestamp"])
    if event["type"] not in EVENT_TYPES:
        raise MemoryV2Error(f"unsupported event type: {event['type']!r}")
    for field in ("domain", "summary", "source_repository", "builder", "ceo_gate_state", "verification_state"):
        if not isinstance(event[field], str) or not event[field].strip():
            raise MemoryV2Error(f"event field {field!r} must be a non-empty string")
    for field in ("affected_workstreams", "findings", "invariants", "supersedes", "evidence"):
        if not isinstance(event[field], list) or not all(isinstance(item, str) for item in event[field]):
            raise MemoryV2Error(f"event field {field!r} must be a list of strings")
    source_sha = event.get("source_sha")
    if source_sha is not None and (not isinstance(source_sha, str) or not SHA_RE.fullmatch(source_sha)):
        raise MemoryV2Error("source_sha must be a 40-character lowercase Git SHA when present")
    source_pr = event.get("source_pr")
    if source_pr is not None and (not isinstance(source_pr, int) or source_pr < 1):
        raise MemoryV2Error("source_pr must be a positive integer when present")
    is_canonical = bool(event.get("canonical", canonical if canonical is not None else False))
    state = event["verification_state"]
    if is_canonical and state not in VERIFIED_STATES:
        raise MemoryV2Error(f"canonical event {event_id} requires verified state; got {state!r}")
    if not is_canonical and state not in VERIFIED_STATES | PENDING_STATES:
        raise MemoryV2Error(f"unknown verification_state: {state!r}")
    if state == "builder_report" and is_canonical:
        raise MemoryV2Error("builder reports cannot be canonical without CEO or independent verification")
    _scan_for_secrets(event)
    normalized = json.loads(json.dumps(event, sort_keys=True, ensure_ascii=False))
    normalized["canonical"] = is_canonical
    return normalized


def _safe_relative(root: Path, rel: str) -> Path:
    if not isinstance(rel, str) or not rel or rel.startswith("/"):
        raise MemoryV2Error(f"invalid relative path: {rel!r}")
    target = (root / rel).resolve()
    root_resolved = root.resolve()
    if target != root_resolved and root_resolved not in target.parents:
        raise MemoryV2Error(f"path escapes Memory repository: {rel!r}")
    return target


def _event_path(root: Path, event_id: str, canonical: bool) -> Path:
    return root / "events" / ("records" if canonical else "pending") / f"{event_id}.json"


def _existing_event(root: Path, event_id: str) -> tuple[Path, dict[str, Any]] | None:
    for path in (_event_path(root, event_id, True), _event_path(root, event_id, False)):
        if path.exists():
            try:
                return path, json.loads(path.read_text(encoding="utf-8"))
            except json.JSONDecodeError as exc:
                raise MemoryV2Error(f"existing event is invalid JSON: {path}") from exc
    return None


def _write_json_atomic(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as handle:
        json.dump(payload, handle, indent=2, sort_keys=True, ensure_ascii=False)
        handle.write("\n")
        temporary = Path(handle.name)
    temporary.replace(path)


def ingest_events(root: Path, events: list[dict[str, Any]], *, canonical_records: list[dict[str, str]] | None = None, validate_after: bool = True) -> list[IngestResult]:
    """Apply events and optional canonical record writes transactionally."""
    if not isinstance(events, list) or not events:
        raise MemoryV2Error("events must be a non-empty list")
    normalized = [validate_event(event) for event in events]
    ids = [event["event_id"] for event in normalized]
    if len(ids) != len(set(ids)):
        raise MemoryV2Error("duplicate event_id in update payload")
    records = canonical_records or []
    for record in records:
        path = _safe_relative(root, record.get("path"))
        rel = path.relative_to(root).as_posix()
        allowed = ("decisions/records/", "workstreams/", "tasks/records/", "findings/records/", "architecture/", "history/", "state/records/", "_meta/", "builder/", "events/")
        if not rel.startswith(allowed):
            raise MemoryV2Error(f"canonical record path is outside approved Memory namespaces: {rel}")
        if not isinstance(record.get("content"), str):
            raise MemoryV2Error(f"canonical record content must be text: {rel}")
        _scan_for_secrets(record["content"], rel)
    touched: list[tuple[Path, bytes | None]] = []
    results: list[IngestResult] = []
    try:
        for event in normalized:
            existing = _existing_event(root, event["event_id"])
            if existing:
                old_path, old_payload = existing
                if old_payload != event:
                    raise MemoryV2Error(f"event_id already exists with a different payload: {event['event_id']}")
                results.append(IngestResult(event["event_id"], old_path.relative_to(root).as_posix(), False))
                continue
            path = _event_path(root, event["event_id"], bool(event["canonical"]))
            touched.append((path, path.read_bytes() if path.exists() else None))
            _write_json_atomic(path, event)
            results.append(IngestResult(event["event_id"], path.relative_to(root).as_posix(), True))
        for record in records:
            path = _safe_relative(root, record["path"])
            touched.append((path, path.read_bytes() if path.exists() else None))
            path.parent.mkdir(parents=True, exist_ok=True)
            temporary = path.with_suffix(path.suffix + ".tmp")
            temporary.write_text(record["content"].rstrip() + "\n", encoding="utf-8")
            temporary.replace(path)
        if validate_after:
            from .validate import validate
            report = validate(root, "v1")
            if report.errors:
                raise MemoryV2Error(f"post-update validation failed with {report.errors} error(s)")
    except Exception:
        for path, old in reversed(touched):
            if old is None:
                path.unlink(missing_ok=True)
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(old)
        raise
    return results


def read_manifest(root: Path) -> dict[str, Any]:
    path = root / "_meta" / "MEMORY_V2.json"
    if not path.exists():
        raise MemoryV2Error("_meta/MEMORY_V2.json is missing")
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise MemoryV2Error("_meta/MEMORY_V2.json is invalid JSON") from exc
    if value.get("memory_version") != 2:
        raise MemoryV2Error("MEMORY_V2.json does not declare memory_version=2")
    return value


def freshness_state(canonical_updated_at: str, source_meaningful_at: str, *, aging_hours: float = 6.0, stale_hours: float = 24.0) -> str:
    canonical = parse_timestamp(canonical_updated_at, "canonical_updated_at")
    source = parse_timestamp(source_meaningful_at, "source_meaningful_at")
    lag_hours = max(0.0, (source - canonical).total_seconds() / 3600.0)
    if lag_hours > stale_hours:
        return "STALE"
    if lag_hours > aging_hours:
        return "AGING"
    return "FRESH"


def file_sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


PACKET_SPECS: dict[str, tuple[str, list[str]]] = {
    "BUILDER_A_RESEARCH": (
        "Builder A — Research Owner",
        ["decisions/records/DEC-0024.md", "workstreams/TOP5-RESEARCH.md", "events/records/EVT-20260910-001.json", "events/records/EVT-20260910-002.json", "events/records/EVT-20260913-003.json"],
    ),
    "BUILDER_B_PRODUCTION": (
        "Builder B — Production Owner",
        ["decisions/records/DEC-0024.md", "workstreams/TOP5-PRODUCTION.md", "workstreams/TOP5-SHADOW-READINESS.md", "events/records/EVT-20260913-004.json", "events/records/EVT-20260913-005.json"],
    ),
    "BUILDER_C_MEMORY": (
        "Builder C — Memory and Observability Owner",
        ["_meta/MEMORY_V2.json", "_meta/EVENT_MODEL.md", "_meta/UPDATE_PROTOCOL.md", "architecture/MEMORY_V2.md", "workstreams/MEMORY-V2.md", "SETUP.md"],
    ),
    "CEO_SUMMARY": (
        "CEO summary context",
        ["00_HOME.md", "CURRENT_STATE.md", "CURRENT_BLOCKERS.md", "CURRENT_PRIORITIES.md", "decisions/INDEX.md", "workstreams/TOP5-RESEARCH.md", "workstreams/TOP5-SHADOW-READINESS.md"],
    ),
}


def _bounded_text(root: Path, rel: str, limit: int = 7000) -> str:
    path = root / rel
    if not path.exists():
        return f"[missing: {rel}]"
    text = path.read_text(encoding="utf-8", errors="replace")
    return text if len(text) <= limit else text[:limit] + "\n\n[packet truncated at bounded source limit]\n"


def build_context_packets(root: Path) -> dict[str, int]:
    """Build bounded role packets; never recursively loads the vault."""
    output = root / "builder" / "context"
    output.mkdir(parents=True, exist_ok=True)
    counts: dict[str, int] = {}
    for key, (title, paths) in PACKET_SPECS.items():
        pieces = [
            V2_GENERATED_MARKER,
            f"# {title}",
            "",
            "This packet is generated and bounded. Read only the listed canonical records; do not recursively load the vault.",
            "",
            "## Included canonical paths",
            "",
        ]
        pieces.extend(f"- `{path}`" for path in paths)
        for path in paths:
            pieces.extend(["", f"## {path}", "", _bounded_text(root, path)])
        text = "\n".join(pieces).rstrip() + "\n"
        (output / f"{key}.md").write_text(text, encoding="utf-8")
        counts[key] = len(text)
    current = output / "BUILDER_C_MEMORY.md"
    if current.exists():
        (root / "builder" / "CURRENT_CONTEXT_PACKET.md").write_text(current.read_text(encoding="utf-8"), encoding="utf-8")
    return counts


def render_v2_projections(root: Path, registry: Any | None = None) -> None:
    """Refresh the V2 home/current views from canonical records."""
    manifest = read_manifest(root)
    if registry is None:
        from .registry import Registry
        registry = Registry(root).scan()
    active = [o for o in registry.objects if o.object_type == "task" and o.status in {"approved", "active"}]
    task_id = active[0].object_id if active else "NONE"
    source_sha = manifest.get("source_main_sha", "UNRESOLVED")
    source_release = manifest.get("source_latest_meaningful_sha", "UNRESOLVED")
    memory_status = manifest.get("canonical_status", "FRESH")
    marker = V1_GENERATED_MARKER + "\n" + V2_GENERATED_MARKER

    home = "\n".join([
        "---", "type: generated-view", "status: current", "generated: true", "---", marker,
        "# SportsBrain Home", "", "## SPORTSBRAIN NOW", "",
        f"- Source main SHA at audit: `{source_sha}`",
        f"- Latest meaningful source merge: `{source_release}`",
        f"- Canonical Memory: **{memory_status}**",
        f"- Current Builder task: **{task_id}**",
        "- Near-live view: [[_live/LIVE_STATUS]]", "",
        "## CURRENT BUILDERS", "",
        "- **Builder A — Research:** Top-5 final audit remains active; 2425/2526 remain sealed.",
        "- **Builder B — Production:** PR #56 Shadow Readiness is not merged and has no live activation.",
        "- **Builder C — Memory/Observability:** Memory V2 and safe Obsidian sync are the current delivery.", "",
        "## TOP-5 PROGRESS", "",
        "- Generic research framework is complete for five leagues; BL1 v7 parity is required and recorded.",
        "- Production architecture is complete, disabled by default, and has no active Top-5 registration.",
        "- Shadow Readiness is pending CEO review of request/quota bulk-modeling corrections.",
        "- Champions League remains after Top-5 completion.", "",
        "## STABILITY", "",
        "- Stability Engineering is technically complete according to the current canonical handoff.",
        "- The formal 72h Stability Soak is **deferred** for the external free-quota dependency; it was not fabricated or started.", "",
        "## OPEN CEO GATES", "",
        "- [[decisions/records/DEC-0024]] — exact Signal-Time values remain unapproved.",
        "- [[workstreams/TOP5-SHADOW-READINESS]] — PR #56 review and request/quota corrections.",
        "- [[workstreams/STABILITY-ENGINEERING]] — formal soak only after quota dependency is resolved.", "",
        "## BLOCKERS", "",
        "- External free-quota dependency for the 72h soak.",
        "- No deployable Top-5 edge claim without the required research, timing, provider, shadow, and rollout gates.", "",
        "## LATEST DECISIONS", "",
        "- CODEX is the sole SportsBrain builder platform; logical Builder A/B/C roles remain separated.",
        "- Canonical Memory and near-live operational status are separate layers.",
        "- Signal-Time uses an event-relative bounded window with explicit lead/age/idempotency constraints; exact values are not approved.", "",
        "## RECENT COMPLETIONS", "",
        "- PR #54 accepted as safe historical baseline.",
        "- PR #55 merged at `b4d6765f79b20ca2f2c3d3b323ee2f666a1449ad`.",
        "- Provider diagnostics, odds-refresh performance, and runtime artifact isolation were hardened.", "",
        "## MEMORY FRESHNESS", "",
        f"The canonical view is **{memory_status}** relative to the audited source SHA. Open [[_live/LIVE_STATUS]] for current lag, sync, CI, and runtime health.",
        "",
    ])
    (root / "00_HOME.md").write_text(home, encoding="utf-8")

    state = "\n".join([
        "---", "type: generated-view", "status: current", "generated: true", "---", marker,
        "# Current State", "", "## Technical baseline", "",
        f"- Source main SHA at last audit: `{source_sha}`",
        f"- Latest meaningful source release/merge: `{source_release}`",
        f"- Canonical Memory freshness: **{memory_status}**",
        f"- Current Builder task: **{task_id}**",
        "- P0-A through P0-C historical production gates remain recorded; later runtime and research evidence is classified separately.", "",
        "## Workstreams", "",
        "- **Stability Engineering** — technically complete; formal 72h soak deferred on external quota.",
        "- **Top-5 Research** — baseline complete; final audit active; no sealed-data access.",
        "- **Top-5 Production Architecture** — complete, disabled by default.",
        "- **Top-5 Shadow Readiness** — current Builder B workstream; PR #56 not merged.",
        "- **Memory V2** — current Builder C workstream; CEO review required for release.", "",
        "Operational source health and runtime-only events belong in [[_live/LIVE_STATUS]], not canonical Memory history.", "",
    ])
    (root / "CURRENT_STATE.md").write_text(state, encoding="utf-8")

    priorities = "\n".join([
        "---", "type: generated-view", "status: current", "generated: true", "---", marker,
        "# Current Priorities", "",
        f"- Audited source main SHA: `{source_sha}`", "",
        "1. Complete CEO review of **TASK-MEM-V2-001** and the Memory V2 release branch.",
        "2. Builder A completes the Top-5 final audit under true A/B/A' contamination, BL1 parity, corrected statistics, and sealed-data rules.",
        "3. Builder B resolves the PR #56 request/quota bulk-modeling review items; keep Shadow Readiness disabled.",
        "4. Resolve the external free-quota dependency before starting the formal 72h Stability Soak.",
        "5. Keep Champions League after Top-5 completion.", "",
        "Historical P0 order remains A → B → C → D; it is not a reason to reactivate completed workstreams.", "",
    ])
    (root / "CURRENT_PRIORITIES.md").write_text(priorities, encoding="utf-8")

    blockers = "\n".join([
        "---", "type: generated-view", "status: current", "generated: true", "---", marker,
        "# Current Blockers", "", "## Deferred dependencies", "",
        f"- Audited source main SHA: `{source_sha}`", "",
        "- External free-quota dependency blocks the formal 72h Stability Soak. The soak has not been started or fabricated.", "",
        "## Active CEO gates", "",
        "- PR #56 Shadow Readiness remains unmerged and disabled pending reviewed request/quota bulk-modeling corrections.",
        "- Exact production Signal-Time values are not approved.",
        "- No Top-5 deployable-edge claim is allowed without the full research, timing, provider, shadow, and rollout gates.", "",
        "## Historical P0 findings", "",
        "P0-A historical findings are resolved production and are not current blockers. Runtime-only noise is visible in [[_live/LIVE_STATUS]].", "",
    ])
    (root / "CURRENT_BLOCKERS.md").write_text(blockers, encoding="utf-8")
