from __future__ import annotations
from dataclasses import dataclass, asdict
from pathlib import Path
import re
from .registry import Registry, RegistryIssue
from .graph import Graph
from .schema import SchemaStore, validate_meta

@dataclass
class ValidationReport:
    profile:str
    issues:list[RegistryIssue]
    object_count:int
    id_count:int
    status_counts:dict[str,int]
    @property
    def errors(self):
        return sum(1 for i in self.issues if i.severity in {'FATAL','ERROR'})
    @property
    def warnings(self):
        return sum(1 for i in self.issues if i.severity=='WARNING')
    def to_dict(self):
        return {
            'profile':self.profile,'errors':self.errors,'warnings':self.warnings,
            'object_count':self.object_count,'id_count':self.id_count,
            'status_counts':self.status_counts,'issues':[asdict(i) for i in self.issues]
        }

def _structured(path:str)->bool:
    return path.startswith((
        'state/records/','tasks/records/','findings/records/','decisions/records/',
        'components/','jobs/','writers/','models/','datasets/','providers/',
        'evidence/records/','verifications/records/','tests/records/','workstreams/'
    ))

def validate(root:Path,profile='v1'):
    reg=Registry(root).scan()
    graph=Graph(reg).build()
    issues=[*reg.issues,*graph.issues]
    store=SchemaStore(root/'_meta'/'schemas')

    for o in reg.objects:
        if not o.object_type:
            if profile=='v1' and _structured(o.relpath):
                issues.append(RegistryIssue('ERROR','MISSING_TYPE','structured object missing type',o.relpath))
            continue
        schema=store.get(o.object_type)
        if schema:
            for s in validate_meta(o.meta,schema):
                sev=s.severity
                if s.code=='SCHEMA_UNKNOWN_FIELD':
                    sev='WARNING'
                issues.append(RegistryIssue(sev,s.code,s.message,o.relpath))
        elif profile=='v1' and _structured(o.relpath):
            if not o.status:
                issues.append(RegistryIssue('ERROR','MISSING_STATUS','structured object missing status',o.relpath))

    states=[o for o in reg.objects if o.object_type=='project-state' and o.status=='current']
    if len(states)!=1:
        issues.append(RegistryIssue('ERROR','CURRENT_STATE_CARDINALITY',f'expected 1 current project-state, got {len(states)}'))

    active=[o for o in reg.objects if o.object_type=='task' and o.status in {'approved','active'}]
    if len(active)>1:
        issues.append(RegistryIssue('ERROR','MULTIPLE_ACTIVE_TASKS',','.join(o.object_id or o.relpath for o in active)))

    by_id=reg.by_id
    for view,should_open in [('findings/OPEN.md',True),('findings/RESOLVED.md',False)]:
        p=root/view
        if not p.exists():
            issues.append(RegistryIssue('ERROR','MISSING_GENERATED_VIEW',view))
            continue
        ids=re.findall(r'FND-\d{8}-\d{3}',p.read_text(encoding='utf-8'))
        for fid in ids:
            o=by_id.get(fid)
            if not o:
                continue
            is_open=o.status in {'open','observed','confirmed','accepted','in_progress','resolved_candidate'}
            if is_open!=should_open:
                issues.append(RegistryIssue('ERROR','FINDING_VIEW_DRIFT',f'{fid} status={o.status} in wrong view',view))

    generated=['00_HOME.md','CURRENT_STATE.md','CURRENT_TASK.md','CURRENT_BLOCKERS.md','CURRENT_PRIORITIES.md','findings/OPEN.md','findings/RESOLVED.md']
    generated += [str(p.relative_to(root)) for p in (root/'mocs').glob('*.md')]
    generated += [str(p.relative_to(root)) for p in (root/'views').glob('*.md')]
    for rel in generated:
        p=root/rel
        if not p.exists() or 'GENERATED BY SportsBrainMemory V1' not in p.read_text(encoding='utf-8'):
            issues.append(RegistryIssue('ERROR','GENERATED_VIEW_MARKER',f'{rel} missing generated marker',rel))

    secretp=[re.compile(r'\bsk-[A-Za-z0-9]{20,}\b'),re.compile(r'\bghp_[A-Za-z0-9]{20,}\b')]
    for p in root.rglob('*'):
        if not p.is_file() or '.memory-build' in p.parts or p.suffix not in {'.md','.json','.py'}:
            continue
        txt=p.read_text(encoding='utf-8',errors='ignore')
        for pat in secretp:
            if pat.search(txt):
                issues.append(RegistryIssue('ERROR','POSSIBLE_SECRET','secret-like token detected',str(p.relative_to(root))))

    return ValidationReport(profile,issues,len(reg.objects),len(reg.by_id),reg.status_counts())
