#!/usr/bin/env python3
from pathlib import Path
import re,sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from memorylib.context import build_context
ROOT=Path(__file__).resolve().parents[1]
text=(ROOT/"CURRENT_TASK.md").read_text(encoding="utf-8")
m=re.search(r'(?m)^task_id:\s*"?([^"\n]+)"?\s*$',text)
if not m:
    print("ERROR: no active task_id; zero active tasks is valid, so no packet should be built.",file=sys.stderr); raise SystemExit(2)
r=build_context(ROOT,m.group(1).strip(),"standard",2)
out=ROOT/"builder"/"CURRENT_CONTEXT_PACKET.md"
out.write_text(f"<!-- generated by V1; estimated_tokens={r.estimated_tokens}; hard_limit={r.hard_limit} -->\n"+r.text,encoding="utf-8")
print(f"Built {out.relative_to(ROOT)}"); print(f"Estimated tokens: {r.estimated_tokens}")
