#!/usr/bin/env python3
"""Build a token-bounded Claude context packet from CURRENT_TASK references.

Stdlib only. Does not modify SportsBrain code or Git.
"""
from pathlib import Path
import re, sys

ROOT = Path(__file__).resolve().parents[1]
TASK = ROOT / "CURRENT_TASK.md"
OUT = ROOT / "builder" / "CURRENT_CONTEXT_PACKET.md"
SOFT_TOKEN_LIMIT = 8000

def parse_frontmatter(text):
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}
    lines = text[4:end].splitlines()
    data, current = {}, None
    for raw in lines:
        if not raw.strip():
            continue
        if raw.startswith("  - ") and current:
            data.setdefault(current, []).append(raw[4:].strip().strip('"'))
            continue
        m = re.match(r'^([A-Za-z0-9_]+):\s*(.*)$', raw)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        current = key
        if val == "":
            data[key] = []
        else:
            data[key] = val.strip('"')
    return data

def extract_section(text, anchor):
    if not anchor:
        return text
    # Find markdown heading with exact ID text, case-insensitive.
    pat = re.compile(r'^(#{1,6})\s+' + re.escape(anchor) + r'\s*$', re.I | re.M)
    m = pat.search(text)
    if not m:
        raise ValueError(f"Section {anchor!r} not found")
    level = len(m.group(1))
    start = m.start()
    next_pat = re.compile(r'^#{1,%d}\s+' % level, re.M)
    n = next_pat.search(text, m.end())
    end = n.start() if n else len(text)
    return text[start:end].strip() + "\n"

def load_ref(ref):
    if "#" in ref:
        path_s, anchor = ref.split("#", 1)
    else:
        path_s, anchor = ref, ""
    p = (ROOT / path_s).resolve()
    if ROOT.resolve() not in p.parents and p != ROOT.resolve():
        raise ValueError(f"Reference escapes memory root: {ref}")
    text = p.read_text(encoding="utf-8")
    return path_s, extract_section(text, anchor)

task_text = TASK.read_text(encoding="utf-8")
meta = parse_frontmatter(task_text)
refs = meta.get("required_context", [])
task_id = meta.get("task_id", "UNKNOWN")

parts = [
    "# SportsBrain Current Context Packet",
    "",
    f"**Task:** {task_id}",
    "",
    "## Bootstrap",
    "",
    (ROOT/"BOOTSTRAP.md").read_text(encoding="utf-8"),
    "",
    "## Current State",
    "",
    (ROOT/"CURRENT_STATE.md").read_text(encoding="utf-8"),
    "",
    "## Current Task",
    "",
    task_text,
]
for ref in refs:
    path_s, content = load_ref(ref)
    parts += ["", f"## Context: `{ref}`", "", content]

packet = "\n".join(parts).strip() + "\n"
est_tokens = max(1, len(packet) // 4)
header = (
    f"<!-- generated by tools/build_context.py; estimated_tokens={est_tokens}; "
    f"soft_limit={SOFT_TOKEN_LIMIT} -->\n"
)
packet = header + packet
OUT.write_text(packet, encoding="utf-8")

print(f"Built {OUT.relative_to(ROOT)}")
print(f"Estimated tokens: {est_tokens}")
if est_tokens > SOFT_TOKEN_LIMIT:
    print("ERROR: context packet exceeds soft token limit; narrow CURRENT_TASK required_context.", file=sys.stderr)
    sys.exit(2)
