#!/usr/bin/env python3
"""Deterministic Obsidian graph analysis for the operational Memory.

The graph is derived only from Markdown wikilinks and frontmatter. It never
edits the vault. Navigation notes (MOCs, indexes, and generated views) are
reported separately so a healthy semantic graph cannot hide behind one giant
home/index hub.
"""
from __future__ import annotations

import argparse
import json
from collections import Counter, deque
from pathlib import Path
from statistics import mean, median
import sys
import re

TOOLS = Path(__file__).resolve().parent
if str(TOOLS) not in sys.path:
    sys.path.insert(0, str(TOOLS))

from validate_operational_memory import markdown_files, parse_frontmatter  # noqa: E402


WIKILINK = re.compile(r"\[\[([^\]]+)\]\]")
HISTORICAL_PARTS = {"history", "templates", "tests", "__pycache__", ".git", "_live"}
SUPPORT_TYPES = {
    "generated-view",
    "memory-home",
    "setup-guide",
    "bootstrap",
    "validation-report",
}
HISTORICAL_STATUSES = {"superseded", "completed", "retired"}


def _target_path(root: Path, raw: str) -> Path | None:
    target = raw.split("|", 1)[0].split("#", 1)[0].strip()
    if not target or target.startswith(("http://", "https://", "mailto:")):
        return None
    if target.lstrip("/").startswith("_live/"):
        # _live is generated by the user-level synchronizer and may not exist
        # in a Git checkout. It is intentionally outside the canonical graph.
        return None
    candidate = root / target.lstrip("/")
    if candidate.suffix == "":
        candidate = candidate.with_suffix(".md")
    return candidate


def _is_navigation(rel: str) -> bool:
    return (
        rel == "00_HOME.md"
        or rel.startswith("mocs/")
        or rel.startswith("views/")
        or rel.endswith("/INDEX.md")
        or rel == "README.md"
    )


def _is_historical_or_support(rel: str, meta: dict[str, str]) -> bool:
    parts = set(Path(rel).parts)
    return bool(parts & HISTORICAL_PARTS) or meta.get("type") in SUPPORT_TYPES


def _is_canonical(meta: dict[str, str]) -> bool:
    return meta.get("canonical", "").lower() == "true"


def _is_operational_canonical(rel: str, meta: dict[str, str]) -> bool:
    return _is_canonical(meta) and not _is_historical_or_support(rel, meta) and meta.get("status") not in HISTORICAL_STATUSES


def _components(nodes: set[str], adjacency: dict[str, set[str]]) -> list[list[str]]:
    remaining = set(nodes)
    result: list[list[str]] = []
    while remaining:
        start = min(remaining)
        queue = deque([start])
        remaining.remove(start)
        component: list[str] = []
        while queue:
            node = queue.popleft()
            component.append(node)
            for neighbor in sorted(adjacency.get(node, set())):
                if neighbor in remaining:
                    remaining.remove(neighbor)
                    queue.append(neighbor)
        result.append(sorted(component))
    return sorted(result, key=lambda item: (-len(item), item[0]))


def analyze(root: Path) -> dict[str, object]:
    root = root.resolve()
    paths = markdown_files(root)
    rel_paths = {path.relative_to(root).as_posix(): path for path in paths}
    metadata = {rel: parse_frontmatter(path) for rel, path in rel_paths.items()}
    adjacency = {rel: set() for rel in rel_paths}
    outgoing = {rel: set() for rel in rel_paths}
    incoming = {rel: set() for rel in rel_paths}
    broken: list[dict[str, str]] = []
    total_internal_wikilinks = 0

    for rel, path in rel_paths.items():
        text = path.read_text(encoding="utf-8", errors="replace")
        for match in WIKILINK.finditer(text):
            candidate = _target_path(root, match.group(1))
            if candidate is None:
                continue
            target_rel = candidate.relative_to(root).as_posix() if candidate.is_relative_to(root) else str(candidate)
            if target_rel not in rel_paths:
                broken.append({"source": rel, "target": match.group(1)})
                continue
            total_internal_wikilinks += 1
            if target_rel == rel:
                continue
            outgoing[rel].add(target_rel)
            incoming[target_rel].add(rel)
            adjacency[rel].add(target_rel)
            adjacency[target_rel].add(rel)

    degree = {rel: len(neighbors) for rel, neighbors in adjacency.items()}
    canonical = sorted(rel for rel, meta in metadata.items() if _is_canonical(meta))
    operational = sorted(rel for rel, meta in metadata.items() if _is_operational_canonical(rel, meta))
    components = _components(set(rel_paths), adjacency)
    component_of = {rel: index for index, component in enumerate(components) for rel in component}
    canonical_components = _components(set(operational), adjacency)
    largest = components[0] if components else []
    largest_canonical = sum(rel in set(operational) for rel in largest)
    operational_component_count = len(canonical_components)
    largest_component_pct = (100.0 * largest_canonical / len(operational)) if operational else 100.0
    navigation_only = sorted(
        rel for rel in operational
        if degree[rel] > 0 and all(_is_navigation(neighbor) for neighbor in adjacency[rel])
    )
    isolated = sorted(rel for rel in rel_paths if degree[rel] == 0)
    isolated_canonical = sorted(rel for rel in operational if degree[rel] == 0)
    degree_one = sorted(rel for rel in rel_paths if degree[rel] == 1)
    degree_one_canonical = sorted(rel for rel in operational if degree[rel] == 1)
    dead_ends = sorted(rel for rel in operational if not outgoing[rel] and incoming[rel])
    degrees = list(degree.values())
    sorted_hubs = sorted(
        (
            {
                "path": rel,
                "degree": degree[rel],
                "canonical": _is_canonical(metadata[rel]),
                "type": metadata[rel].get("type", "NONE"),
            }
            for rel in rel_paths
        ),
        key=lambda item: (-int(item["degree"]), item["path"]),
    )
    hub_cutoff = max(10, int(0.95 * max(degrees, default=0)))
    excessive_hubs = [item for item in sorted_hubs if int(item["degree"]) >= hub_cutoff and int(item["degree"]) > 10]
    distribution: dict[str, dict[str, float | int]] = {}
    for note_type in sorted({meta.get("type", "NONE") for meta in metadata.values()}):
        values = [degree[rel] for rel in rel_paths if metadata[rel].get("type", "NONE") == note_type]
        distribution[note_type] = {
            "notes": len(values),
            "canonical": sum(_is_canonical(metadata[rel]) for rel in rel_paths if metadata[rel].get("type", "NONE") == note_type),
            "mean_degree": round(mean(values), 4) if values else 0.0,
            "median_degree": median(values) if values else 0,
        }
    unique_edges = sum(degree.values()) // 2
    return {
        "notes": len(rel_paths),
        "canonical_notes": len(canonical),
        "canonical_operational_notes": len(operational),
        "total_internal_wikilinks": total_internal_wikilinks,
        "unique_edges": unique_edges,
        "broken_links": broken,
        "broken_link_count": len(broken),
        "isolated_nodes": isolated,
        "isolated_node_count": len(isolated),
        "isolated_canonical_nodes": isolated_canonical,
        "isolated_canonical_count": len(isolated_canonical),
        "degree_one_nodes": degree_one,
        "degree_one_count": len(degree_one),
        "degree_one_canonical_nodes": degree_one_canonical,
        "degree_one_canonical_count": len(degree_one_canonical),
        "connected_components": len(components),
        "canonical_operational_components": operational_component_count,
        "component_sizes": [len(component) for component in components],
        "largest_component_size": len(largest),
        "largest_component_canonical_operational_pct": round(largest_component_pct, 4),
        "median_degree": median(degrees) if degrees else 0,
        "mean_degree": round(mean(degrees), 4) if degrees else 0.0,
        "maximum_degree": max(degrees, default=0),
        "top_hubs": sorted_hubs[:10],
        "excessive_hubs": excessive_hubs,
        "moc_only_nodes": sorted(
            rel for rel in rel_paths if degree[rel] > 0 and not _is_navigation(rel) and all(_is_navigation(n) for n in adjacency[rel])
        ),
        "moc_only_canonical_nodes": navigation_only,
        "moc_only_canonical_count": len(navigation_only),
        "dead_end_operational_nodes": dead_ends,
        "dead_end_operational_count": len(dead_ends),
        "component_of": component_of,
        "distribution_by_type": distribution,
        "note_metrics": {
            rel: {
                "outgoing_degree": len(outgoing[rel]),
                "incoming_degree": len(incoming[rel]),
                "total_degree": degree[rel],
                "canonical": _is_canonical(metadata[rel]),
                "operational_canonical": _is_operational_canonical(rel, metadata[rel]),
                "type": metadata[rel].get("type", "NONE"),
                "component": component_of[rel],
                "moc_only": rel in navigation_only,
                "isolated": degree[rel] == 0,
                "dead_end": rel in dead_ends,
            }
            for rel in sorted(rel_paths)
        },
    }


def quality_issues(result: dict[str, object], allowlist: dict[str, str] | None = None) -> list[dict[str, str]]:
    allowlist = allowlist or {}
    issues: list[dict[str, str]] = []
    if len(allowlist) > 10:
        issues.append({"severity": "ERROR", "code": "EXCESSIVE_ALLOWLIST", "message": "more than 10 graph exceptions"})
    for path in result["broken_links"]:
        issues.append({"severity": "ERROR", "code": "BROKEN_WIKILINK", "message": f"{path['source']} -> {path['target']}"})
    for key in ("isolated_canonical_nodes", "degree_one_canonical_nodes"):
        for rel in result[key]:
            if rel not in allowlist:
                issues.append({"severity": "ERROR", "code": key.upper(), "message": rel})
    for rel in result["moc_only_canonical_nodes"]:
        if rel not in allowlist:
            issues.append({"severity": "ERROR", "code": "MOC_ONLY_CANONICAL", "message": rel})
    if int(result["canonical_operational_components"]) > 1:
        issues.append({"severity": "ERROR", "code": "DISCONNECTED_CANONICAL_COMPONENTS", "message": str(result["canonical_operational_components"])})
    if float(result["largest_component_canonical_operational_pct"]) < 95.0:
        issues.append({"severity": "ERROR", "code": "LARGEST_COMPONENT_COVERAGE", "message": f"{result['largest_component_canonical_operational_pct']}% < 95%"})
    return issues


def _main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--validate", action="store_true")
    args = parser.parse_args()
    result = analyze(args.root)
    if args.validate:
        result["quality_issues"] = quality_issues(result)
    if args.json:
        print(json.dumps(result, indent=2, ensure_ascii=False, sort_keys=True))
    else:
        print(f"Graph: {result['notes']} notes, {result['canonical_notes']} canonical, {result['unique_edges']} unique edges")
        print(f"Components: {result['connected_components']} total; largest={result['largest_component_size']} ({result['largest_component_canonical_operational_pct']}% operational canonical)")
        print(f"Isolates: {result['isolated_node_count']} total; {result['isolated_canonical_count']} operational canonical")
        print(f"Degree-1: {result['degree_one_count']} total; {result['degree_one_canonical_count']} operational canonical")
        print(f"MOC-only: {result['moc_only_canonical_count']} operational canonical; broken={result['broken_link_count']}")
        if args.validate:
            for issue in result["quality_issues"]:
                print(f"{issue['severity']}: {issue['code']} {issue['message']}")
    return 1 if args.validate and result["quality_issues"] else 0


if __name__ == "__main__":
    raise SystemExit(_main())
